#pragma once
#include "Globals.hpp"

namespace quartz::client
{
    template<typename T>
    bool parseNumber(std::string_view value, T& result);

    template<typename T>
    bool readProcessMemoryValue(pid_t pid, std::uintptr_t address, T& value, std::string& error);

    std::string makeGeneratedShader(const std::string_view body);
    std::string shaderPresetId(const std::string_view name);
    void parameterizeShaderPreset(ShaderPreset& preset);
    std::string makeSourceShader(const std::string_view declaration, const std::string_view body);
    std::vector<ShaderPreset> buildShaderPresets();
    const ReactiveKeyBinding* findReactiveKeyBinding(const std::uint16_t key) noexcept;
    TextEditor::Palette shaderEditorPalette();
    void configureShaderEditor(TextEditor& editor, const std::string_view source);
    void initializeShaderEditors(ShaderEditorState& state, const std::string_view vertexSource, const std::string_view fragmentSource);
    std::filesystem::path settingsPath();
    std::filesystem::path vertexShaderPath();
    std::filesystem::path fragmentShaderPath();
    std::filesystem::path shaderMaterialPath();
    void setShaderSource(std::array<char, ShaderSourceCapacity>& destination, const std::string_view source);
    bool loadTextFile(const std::filesystem::path& path, std::array<char, ShaderSourceCapacity>& source);
    bool saveTextFile(const std::filesystem::path& path, const std::array<char, ShaderSourceCapacity>& source);
    bool replaceAll(std::string& value, const std::string_view from, const std::string_view to);
    bool migrateObsoleteShaderSource(std::array<char, ShaderSourceCapacity>& source);
    std::filesystem::path shaderLibraryPath();
    bool loadTextFileString(const std::filesystem::path& path, std::string& source);
    std::optional<std::pair<std::string, std::string>> parseShaderAnnotation(const std::string_view source);
    void refreshShaderLibrary();
    const ShaderPreset* findShaderPresetById(const std::string_view id) noexcept;
    int shaderPresetIndexById(const std::string_view id) noexcept;
    bool importShaderToLibrary(const std::filesystem::path& sourcePath, std::string& importedId, std::string& error);
    std::string shaderPresetIdByIndex(const int index);
    void loadShaderSources(std::array<char, ShaderSourceCapacity>& vertexSource, std::array<char, ShaderSourceCapacity>& fragmentSource);
    int detectShaderPreset(const std::string_view source) noexcept;
    void saveShaderSources(const std::array<char, ShaderSourceCapacity>& vertexSource, const std::array<char, ShaderSourceCapacity>& fragmentSource);
    std::string serializeSettings(const VisualizerSettings& settings);
    std::string_view trimSettingValue(std::string_view value) noexcept;
    bool parseBool(const std::string_view value, bool& result);
    void loadSettings(VisualizerSettings& settings);
    bool saveSettings(const VisualizerSettings& settings);
    HSV rgbToHsv(const Color32 color) noexcept;
    Color32 hsvToRgb(float h, const float s, const float v) noexcept;
    Color32 lerpColor(const Color32 from, const Color32 to, const float amount) noexcept;
    Color32 floatColor(const std::array<float, 3>& color) noexcept;
    void saturate(float& r, float& g, float& b, const float saturation) noexcept;
    std::string shaderMaterialSerializeFloats(const std::array<float, 4>& values, const int count);
    std::string shaderMaterialSerializeInts(const std::array<int, 4>& values, const int count);
    bool parseShaderMaterialFloats(const std::string_view value, std::array<float, 4>& result, const int count);
    bool parseShaderMaterialInts(const std::string_view value, std::array<int, 4>& result, const int count);
    void loadShaderMaterialValueCache();
    bool saveShaderMaterialValueCache();
    std::string prettyUniformLabel(std::string_view name);
    bool isEngineShaderUniform(std::string_view name);
    std::unordered_map<std::string, ShaderUniformMetadata> parseShaderUniformMetadata(const std::string_view vertexSource, const std::string_view fragmentSource);
    int shaderUniformComponents(const GLenum type) noexcept;
    const char* shaderUniformTypeName(const GLenum type) noexcept;
    void applyShaderDiagnostics(TextEditor& editor, const std::string_view log);
    void updateShaderDiagnostics(ShaderEditorState& editors, const std::string& status);
    bool compileShaders(ShaderFramebuffer& framebuffer, ShaderEditorState& editors, const std::array<char, ShaderSourceCapacity>& vertexSource, const std::array<char, ShaderSourceCapacity>& fragmentSource);
    Color32 lerpColorLinear(const Color32 from, const Color32 to, const float amount) noexcept;
    bool switchShaderPreset(ShaderFramebuffer& framebuffer, ShaderTransitionState& transition, ShaderEditorState& editors, std::array<char, ShaderSourceCapacity>& vertexSource, std::array<char, ShaderSourceCapacity>& fragmentSource, VisualizerSettings& settings, const int presetIndex, const double now, const float transitionSeconds, const bool persist = true);
    bool switchShaderId(ShaderFramebuffer& framebuffer, ShaderTransitionState& transition, ShaderEditorState& editors, std::array<char, ShaderSourceCapacity>& vertexSource, std::array<char, ShaderSourceCapacity>& fragmentSource, VisualizerSettings& settings, const std::string_view shaderId, const double now, const float transitionSeconds, const bool persist = true);
    PacketBuffer makePacket(const PacketType type);
    std::string shellQuote(const std::string_view value);
    std::vector<std::byte> readCommand(const std::string& command, const std::size_t maxBytes = 16 * 1024 * 1024);
    std::string bytesToString(const std::vector<std::byte>& bytes);
    std::string trim(std::string value);
    bool commandExists(const std::string_view command);
    std::vector<AudioSourceInfo> enumerateAudioSources();
    std::vector<std::string> split(const std::string_view value, const char delimiter);
    std::string percentDecode(const std::string_view value);
    std::string runtimeLower(std::string_view value);
    std::string runtimeRegexEscape(const std::string_view value);
    bool runtimeRebindModeIsRegex(const ProcessRebindMode mode) noexcept;
    const char* runtimeRebindModeName(const ProcessRebindMode mode) noexcept;
    std::vector<RuntimeProcessInfo> enumerateRuntimeProcesses();
    std::string runtimeProcessDisplayTitle(const RuntimeProcessInfo& process);
    bool runtimeProcessMatchesSearch(const RuntimeProcessInfo& process, const std::string_view loweredQuery);
    std::string runtimeProcessRebindValue(const RuntimeProcessInfo& process, const ProcessRebindMode mode);
    void captureRuntimeRebindPattern(RuntimeBinding& binding, const RuntimeProcessInfo& process);
    bool runtimeProcessMatchesRebind(const RuntimeProcessInfo& process, const RuntimeBinding& binding, const std::regex* regex);
    std::optional<RuntimeProcessInfo> findRuntimeRebindProcess(const RuntimeBinding& binding, std::string& error);
    bool runtimeProcessIsAlive(const pid_t pid) noexcept;
    double runtimeSteadySeconds() noexcept;
    bool tryRuntimeProcessRebind(RuntimeBinding& binding, pid_t& pid, std::string& error);
    std::vector<RuntimeProcessModule> enumerateRuntimeModules(const pid_t pid);
    std::vector<RuntimeProcessRegion> enumerateRuntimeRegions(const pid_t pid);
    int runtimeHexNibble(const char c) noexcept;
    bool parseRuntimeHexPattern(const std::string_view signature, std::vector<std::uint8_t>& bytes, std::vector<std::uint8_t>& masks, std::string& error);
    std::string runtimeNormalizeOpcodeText(std::string value);
    bool runtimeWildcardTextMatch(const std::string_view pattern, const std::string_view value) noexcept;
    std::vector<std::string> parseRuntimeOpcodePattern(const std::string_view specification);
    bool runtimeDecodeInstructionText(const std::span<const std::uint8_t> bytes, const std::uintptr_t address, std::string& text, std::size_t& length);
    bool runtimeDecodeInstructionText(const std::span<const std::uint8_t>, const std::uintptr_t, std::string&, std::size_t&);
    bool runtimeOpcodePatternMatches(const std::span<const std::uint8_t> bytes, const std::uintptr_t address, const std::vector<std::string>& patterns, std::size_t& matchedLength);
    bool readProcessMemoryBlock(const pid_t pid, const std::uintptr_t address, std::span<std::uint8_t> buffer, std::string& error);
    const char* runtimeX64RegisterName(const RuntimeX64Register reg) noexcept;
    std::uint64_t runtimeX64RegisterValue(const user_regs_struct& regs, const RuntimeX64Register reg) noexcept;
    std::vector<pid_t> enumerateRuntimeThreads(const pid_t pid);
    bool runtimePtracePeekUser(const pid_t tid, const std::size_t offset, std::uint64_t& value) noexcept;
    bool runtimePtracePokeUser(const pid_t tid, const std::size_t offset, const std::uint64_t value) noexcept;
    bool runtimeWaitForPtraceStop(const pid_t tid, std::stop_token stop, const double timeoutSeconds, int& status) noexcept;
    void startRuntimeRegisterCapture(RuntimeBinding& binding, const pid_t pid, const std::uintptr_t instruction, const std::intptr_t displacement);
    bool readRuntimeRegisterDisplacement(const RuntimeBinding& binding, const pid_t pid, const std::uintptr_t instruction, std::intptr_t& displacement, std::string& error);
    std::optional<std::uintptr_t> advanceRuntimeRegisterCapture(RuntimeBinding& binding, const pid_t pid, std::string& error);
    std::uint64_t runtimeSignatureConfigurationHash(const RuntimeBinding& binding);
    void resetRuntimeSignatureScan(RuntimeBinding& binding, const bool clearResolved = true);
    bool prepareRuntimeSignatureScan(RuntimeBinding& binding, const pid_t pid, std::string& error);
    bool runtimeSignatureMatches(const std::span<const std::uint8_t> data, const std::size_t offset, const RuntimeBinding& binding) noexcept;
    bool parseRuntimeInteger(const std::string_view text, std::intptr_t& value);
    std::optional<std::uintptr_t> resolveRuntimeAddress(const RuntimeBinding& binding, const pid_t pid, std::string& error, const std::optional<std::uintptr_t> baseOverride = std::nullopt);
    std::optional<std::uintptr_t> advanceRuntimeSignatureScan(RuntimeBinding& binding, const pid_t pid, std::string& error);
    bool readNativeBinding(RuntimeBinding& binding, float& output);
    bool readNativeAddressBinding(RuntimeBinding& binding, float& output);
    std::filesystem::path runtimeBindingsPath();
    std::string runtimeEscape(const std::string_view value);
    std::string runtimeUnescape(const std::string_view value);
    const char* runtimeSourceName(const RuntimeSourceKind source);
    std::vector<std::string_view> runtimeSignalNames(const RuntimeSourceKind source);
    const char* runtimeAggregateOperationName(const RuntimeAggregateOperation operation) noexcept;
    const char* runtimeCompareConditionName(const RuntimeCompareCondition condition) noexcept;
    const char* runtimeMassCompareResultName(const RuntimeMassCompareResult result) noexcept;
    const char* runtimeObjectFieldTypeName(const RuntimeObjectFieldType type) noexcept;
    const char* runtimeObjectPackingName(const RuntimeObjectPacking packing) noexcept;
    const char* runtimeObjectAlignmentName(const RuntimeObjectAlignment alignment) noexcept;
    const char* runtimeBankValueTypeName(const RuntimeBankValueType type) noexcept;
    const char* runtimeActionTargetName(const RuntimeActionTarget target) noexcept;
    bool runtimeActionTargetIsBindingOperation(const RuntimeActionTarget target) noexcept;
    bool runtimeControlTargetIsBindingOperation(const RuntimeControlTarget target) noexcept;
    const char* runtimeActionValueModeName(const RuntimeActionValueMode mode) noexcept;
    const char* runtimeActionWhenName(const RuntimeActionWhen when) noexcept;
    bool runtimeObjectFieldIsFiller(const RuntimeObjectFieldType type) noexcept;
    std::size_t runtimeObjectFieldSize(const RuntimeObjectField& field) noexcept;
    std::size_t runtimeObjectNaturalAlignment(const RuntimeObjectField& field) noexcept;
    std::size_t runtimeObjectPackingBytes(const RuntimeObjectPacking packing) noexcept;
    std::size_t runtimeObjectAlignmentBytes(const RuntimeObjectAlignment alignment) noexcept;
    std::size_t runtimeAlignUp(const std::size_t value, const std::size_t alignment) noexcept;
    std::size_t runtimeObjectFieldOffset(const RuntimeObjectDescriptor& object, const std::uint64_t fieldId, std::size_t* objectSize = nullptr) noexcept;
    std::string runtimeHexAddress(const std::uintptr_t value);
    void drawIndeterminateProgressBar(ImVec2 size);
    void mapSpectrumToColumns(const std::span<const float> analysisBands, std::array<float, Columns>& bands, const VisualizerSettings& settings, const float overallGain);
    void smoothBands(const std::array<float, Columns>& bands, std::array<float, Columns>& smoothedBands, const VisualizerSettings& settings, const float dt);
    void renderAudioRGB(std::array<Color32, MatrixSize>& framebuffer, const std::array<float, Columns>& bands, const VisualizerSettings& settings, const std::optional<Color32> visualizerColor, const float mediaColorAmount, const float wavePhase);
    bool sendFramebuffer(RawUSB& usb, const std::array<Color32, MatrixSize>& framebuffer);
    void applyGlobalBrightness(std::array<Color32, MatrixSize>& framebuffer, const float brightness) noexcept;
    Color32 interpolatePreviewColor(const std::array<Color32, MatrixSize>& framebuffer, const std::uint8_t row, const std::uint8_t column, const float interpolation) noexcept;
    void drawFramebufferPreview(const std::array<Color32, MatrixSize>& framebuffer, const float widthFraction = 0.55f, const float maxWidth = 532.0f, const float interpolation = 0.0f);
    void drawShaderLivePanel(RawUSB& usb, SharedDeviceState& deviceState, const EvdevKeyboard& keyboardInput, const std::array<Color32, MatrixSize>& framebuffer, const float appCpuUsage, const bool scrollLockActive, const bool capsLockActive, VisualizerSettings& settings);
    void drawPerformance(const PerformanceSnapshot& stats);
    void drawTimingProbe(const MatrixTimingProbeResult<ActiveProbeRows>& probe);
    const char* packetTypeLabel(const std::uint16_t type);
    void selectRuntimeProcess(RuntimeBinding& binding, const RuntimeProcessInfo& process);
    bool drawRuntimeTargetSelector(RuntimeBinding& binding, ShaderFramebuffer& shaderFramebuffer);
    bool drawRuntimeProcessSelector(RuntimeBinding& binding, std::vector<RuntimeProcessInfo>& processes);
    const char* runtimeParameterSlotName(const RuntimeParameterSlot slot) noexcept;
    bool drawRuntimeParameterLink(RuntimeBindingEngine& engine, RuntimeBinding& owner, const RuntimeParameterSlot slot);
    bool drawRuntimeLinkedFloat(RuntimeBindingEngine& engine, RuntimeBinding& binding, const RuntimeParameterSlot slot, const char* label, float& value, const float speed = 0.01f, const char* format = "%.3f");
    bool drawRuntimeLinkedBool(RuntimeBindingEngine& engine, RuntimeBinding& binding, const RuntimeParameterSlot slot, const char* label, bool& value);
    bool drawRuntimeBindingReferenceCombo(RuntimeBindingEngine& engine, const char* label, std::uint64_t& id, const std::uint64_t excludeId = 0, const bool unboundOnly = false);
    bool drawRuntimeControlReferenceCombo(RuntimeBindingEngine& engine, const char* label, std::uint64_t& id);
    bool drawRuntimeBankReferenceCombo(RuntimeBindingEngine& engine, const char* label, std::uint64_t& id);
    ImVec4 runtimeStateColor(const bool enabled, const bool good, const bool error = false, const bool waiting = false);
    bool runtimeBindingLooksBoolean(const RuntimeBinding& binding) noexcept;
    void drawRuntimeStateSquare(const char* id, const ImVec4 color);
    bool drawRuntimeActionList(RuntimeBindingEngine& engine, ShaderFramebuffer& shaderFramebuffer, std::vector<RuntimeAction>& actions, const std::uint64_t sourceBindingId, const bool controlOwner);
    bool drawRuntimeReferenceList(RuntimeBindingEngine& engine, RuntimeBinding& binding, const bool showWeights, const bool massCompare = false);
    bool drawRuntimeBinding(RuntimeBindingEngine& engine, ShaderFramebuffer& shaderFramebuffer, RuntimeBinding& binding, bool& erase);
    const char* runtimeControlConditionName(const RuntimeControlCondition condition);
    const char* runtimeControlTargetName(const RuntimeControlTarget target);
    bool drawRuntimeControlMaterialTarget(RuntimeControlRule& control, ShaderFramebuffer& shaderFramebuffer);
    bool drawRuntimeControlRule(RuntimeBindingEngine& engine, ShaderFramebuffer& shaderFramebuffer, RuntimeControlRule& control, bool& erase);
    bool runtimeWriteProcessMemory(const pid_t pid, const std::uintptr_t address, const std::span<const std::uint8_t> bytes, std::string& error);
    bool runtimeParseHexBytes(const std::string_view text, std::vector<std::uint8_t>& bytes, std::string& error);
    std::string runtimeFormatHexBytes(const std::span<const std::uint8_t> bytes);
    void runtimeRefreshMemoryInspector(RuntimeMemoryInspectorState& state);
    RuntimeMemoryInspectorState& runtimeMemoryInspectorState();
    void drawRuntimeMemoryInspector(RuntimeMemoryInspectorState& state);
    void drawRuntimePointers(RuntimeBindingEngine& engine);
    void drawRuntimeObjectDescriptors(RuntimeBindingEngine& engine);
    bool drawProfileHotkey(RuntimeBindingProfile& profile);
    void drawRuntimeValueBank(RuntimeBindingEngine& engine);
    void drawRuntimeProfiles(RuntimeBindingEngine& engine, JavaScriptRuntime& javascript);
    void drawGroupedBindings(RuntimeBindingEngine& engine, ShaderFramebuffer& shaderFramebuffer);
    void drawGroupedControls(RuntimeBindingEngine& engine, ShaderFramebuffer& shaderFramebuffer);
    void drawRuntimeBindingsPage(RuntimeBindingEngine& engine, ShaderFramebuffer& shaderFramebuffer);
    void drawQRPCInspectorPage(RuntimeTelemetry& telemetry);
    void drawUSBProfilerPage(RawUSB& usb, const RuntimeBindingEngine& bindings);
    void drawInputAnalyzerPage(const EvdevKeyboard& keyboard, const ReactiveKeyState& keys, const RuntimeInputAnalytics& analytics);
    void drawRGBProfilerPage(const std::array<Color32, MatrixSize>& framebuffer, const VisualizerSettings& settings, const RuntimeRGBAnalytics& analytics);
    void drawAudioLabPage(AudioSpectrum& audio, const AudioLevelSnapshot& level, const AutoGainState& autoGain, VisualizerSettings& settings, const std::array<float, FFTSize>& analysisBands, const std::array<float, Columns>& mappedBands, const std::array<float, Columns>& smoothedBands);
    void drawTimelinePage(RuntimeTelemetry& telemetry);
    void drawFirmwarePage(const PerformanceSnapshot& performance, const bool hasPerformance, const MatrixTimingProbeResult<ActiveProbeRows>& timingProbe, const bool hasTimingProbe);
    bool defaultAudioSourceButton(const char* id, VisualizerSettings& settings, const VisualizerSettings& defaults, AudioSpectrum& audio);
    void applyDarkTheme();
    float shaderEditorPixelSize(const float zoom) noexcept;
    void initializeShaderEditorFonts();
    std::size_t shaderEditorZoomIndex(float& zoom) noexcept;
    void updateShaderEditorZoomShortcuts(ShaderEditorState& shaderEditor, VisualizerSettings& settings, const bool editorHovered);
    bool renderShaderTextEditor(TextEditor& editor, const char* id, const ImVec2 size, ShaderEditorState& shaderEditor, VisualizerSettings& settings);
    bool drawShaderMaterialEditor(ShaderFramebuffer& shaderFramebuffer, const float maxHeight = 150.0f);
    void drawShaderEditorPage(RawUSB& usb, SharedDeviceState& deviceState, const EvdevKeyboard& keyboardInput, ShaderFramebuffer& shaderFramebuffer, ShaderTransitionState& shaderTransition, ShaderEditorState& shaderEditor, ViewPage& page, std::array<char, ShaderSourceCapacity>& vertexShaderSource, std::array<char, ShaderSourceCapacity>& fragmentShaderSource, std::array<char, ShaderPathCapacity>& vertexLoadPath, std::array<char, ShaderPathCapacity>& fragmentLoadPath, VisualizerSettings& settings, const std::array<Color32, MatrixSize>& framebuffer, const float appCpuUsage, const bool scrollLockActive, const bool capsLockActive);
    void drawPermanentHeader(RawUSB& usb);
    void drawUi(RawUSB& usb, AudioSpectrum& audio, MediaColorProvider& mediaColor, const EvdevKeyboard& keyboardInput, ShaderFramebuffer& shaderFramebuffer, ShaderTransitionState& shaderTransition, ShaderEditorState& shaderEditor, ui::PageManager& pageManager, std::array<char, ShaderSourceCapacity>& vertexShaderSource, std::array<char, ShaderSourceCapacity>& fragmentShaderSource, std::array<char, ShaderPathCapacity>& vertexLoadPath, std::array<char, ShaderPathCapacity>& fragmentLoadPath, VisualizerSettings& settings, const std::array<float, FFTSize>& analysisBands, const std::array<float, Columns>& mappedBands, const std::array<float, Columns>& smoothedBands, const std::array<Color32, MatrixSize>& framebuffer, SharedDeviceState& deviceState, RuntimeBindingEngine& runtimeBindings, JavaScriptRuntime& javascript, RuntimeTelemetry& runtimeTelemetry, const AutoGainState& autoGain, const AudioLevelSnapshot& audioLevel, const ReactiveKeyState& reactiveKeys, const RuntimeInputAnalytics& inputAnalytics, const RuntimeRGBAnalytics& rgbAnalytics, std::uint64_t sentFrames, std::uint64_t droppedFrames, const float appCpuUsage, const bool scrollLockActive, const bool capsLockActive);
}
