#include "quartz/client/runtime/QuickJS.hpp"
#include <filesystem>
#include <fstream>
#include <string_view>

namespace quartz::client
{
    std::string_view runtimeQuickJSTypeDeclarations() noexcept
    {
        static constexpr std::string_view Declarations = R"TS(// Quartz TypeScript scripting SDK
// Generated by Quartz Client. Do not edit this file by hand.

declare module "@quartz/client" {
    export type Address = bigint;
    export type InputKey = number | string;
    export type DisposeReason = "reload" | "disabled" | "removed" | "shutdown";

    export interface Subscription {
        readonly active: boolean;
        dispose(): void;
    }

    export interface ProcessModule {
        readonly base: Address;
        readonly end: Address;
        readonly size: bigint;
        readonly name: string;
        readonly path: string;
    }

    export interface ProcessRegion {
        readonly base: Address;
        readonly end: Address;
        readonly size: bigint;
        readonly readable: boolean;
        readonly writable: boolean;
        readonly executable: boolean;
        readonly path: string;
    }

    export interface ProcessStoppedEvent {
        readonly process: Process;
        readonly time: number;
    }

    export interface Process {
        readonly pid: number;
        readonly name: string;
        readonly exe: string;
        readonly title: string;
        readonly commandLine: string;
        readonly alive: boolean;
        modules(): ProcessModule[];
        regions(): ProcessRegion[];
        on(event: "stopped", callback: (event: ProcessStoppedEvent) => void): Subscription;
    }

    export interface ProcessAPI {
        list(): Process[];
        find(query: number | bigint | string): Process | undefined;
        wait(query: number | bigint | string): Promise<Process>;
    }

    export const Process: ProcessAPI;

    export interface SignatureScanOptions {
        executableOnly?: boolean;
    }

    export interface SignatureProgressEvent {
        readonly scan: SignatureScan;
        readonly progress: number;
        readonly scannedBytes: bigint;
        readonly totalBytes: bigint;
        readonly averageMiBs: number;
    }

    export interface SignatureScan extends Promise<Address> {
        readonly id: bigint;
        readonly process: Process;
        readonly pattern: string;
        readonly progress: number;
        readonly scannedBytes: bigint;
        readonly totalBytes: bigint;
        readonly averageMiBs: number;
        readonly finished: boolean;
        cancel(): void;
        on(event: "progress", callback: (event: SignatureProgressEvent) => void): Subscription;
        on(event: "cancelled", callback: () => void): Subscription;
    }

    export interface SignatureAPI {
        scan(process: Process, pattern: string, options?: SignatureScanOptions): SignatureScan;
    }

    export const Signature: SignatureAPI;

    export interface Registers {
        readonly [name: string]: bigint;
    }

    export interface BreakpointHit {
        readonly time: number;
        readonly process: Process;
        readonly tid: number;
        readonly address: Address;
        readonly registers: Registers;
    }

    export interface BreakpointHitOptions {
        timeout?: number;
    }

    export interface Breakpoint {
        readonly process: Process;
        readonly address: Address;
        readonly armed: boolean;
        arm(): void;
        cancel(): void;
        nextHit(options?: BreakpointHitOptions): Promise<BreakpointHit>;
        on(event: "hit", callback: (event: BreakpointHit) => void): Subscription;
    }

    export interface BreakpointAPI {
        at(process: Process, address: Address | number): Breakpoint;
    }

    export const Breakpoint: BreakpointAPI;

    export interface Field<T> {
        readonly offset: bigint;
        readonly __quartzFieldType?: T;
    }

    export type StructFields = Record<string, Field<unknown>>;
    export type FieldValue<T> = T extends Field<infer TValue> ? TValue : never;

    export interface Struct<TFields extends StructFields = StructFields> {
        readonly fields: TFields;
        at(process: Process, address: Address | number): Pointer<Struct<TFields>>;
    }

    export interface PointerBase {
        /** Process/address metadata use reserved $ names so struct fields can freely use names such as address or process. */
        readonly $process: Process;
        readonly $address: Address;
        readonly $readable: boolean;
        isReadable(): boolean;
        as<TFields extends StructFields>(type: Struct<TFields>): Pointer<Struct<TFields>>;
    }

    export type Pointer<T extends Struct<StructFields>> = PointerBase & {
        [TKey in keyof T["fields"]]: FieldValue<T["fields"][TKey]>;
    };

    export interface FieldAPI {
        Int8(offset: Address | number): Field<number>;
        UInt8(offset: Address | number): Field<number>;
        Int16(offset: Address | number): Field<number>;
        UInt16(offset: Address | number): Field<number>;
        Int32(offset: Address | number): Field<number>;
        UInt32(offset: Address | number): Field<number>;
        Int64(offset: Address | number): Field<bigint>;
        UInt64(offset: Address | number): Field<bigint>;
        Float32(offset: Address | number): Field<number>;
        Float64(offset: Address | number): Field<number>;
        Boolean(offset: Address | number): Field<boolean>;
        Pointer(offset: Address | number): Field<Address | undefined>;
        Pointer<TFields extends StructFields>(offset: Address | number, type: Struct<TFields>): Field<Pointer<Struct<TFields>> | undefined>;
        Struct<TFields extends StructFields>(offset: Address | number, type: Struct<TFields>): Field<Pointer<Struct<TFields>>>;
        Array<T>(offset: Address | number, field: Field<T>, count: number): Field<readonly T[]>;
    }

    export interface StructAPI {
        define<TFields extends StructFields>(fields: TFields): Struct<TFields>;
    }

    export const Field: FieldAPI;
    export const Struct: StructAPI;

    export interface PropertyBaseOptions<T> {
        label?: string;
        group?: string;
        default: T;
        description?: string;
    }

    export interface NumericPropertyOptions extends PropertyBaseOptions<number> {
        min?: number;
        max?: number;
        step?: number;
    }

    export interface Property<T> {
        value: T;
        readonly defaultValue: T;
        reset(): void;
        on(event: "changed", callback: (value: T) => void): Subscription;
    }

    export interface PropertyAPI {
        String(id: string, options: PropertyBaseOptions<string>): Property<string>;
        Boolean(id: string, options: PropertyBaseOptions<boolean>): Property<boolean>;
        Int32(id: string, options: NumericPropertyOptions): Property<number>;
        UInt32(id: string, options: NumericPropertyOptions): Property<number>;
        Float32(id: string, options: NumericPropertyOptions): Property<number>;
        Float64(id: string, options: NumericPropertyOptions): Property<number>;
        Shader(id: string, options: PropertyBaseOptions<string>): Property<string>;
        File(id: string, options: PropertyBaseOptions<string>): Property<string>;
        Directory(id: string, options: PropertyBaseOptions<string>): Property<string>;
        Key(id: string, options: PropertyBaseOptions<InputKey>): Property<InputKey>;
        Enum<T extends string>(id: string, options: PropertyBaseOptions<T> & { values: readonly T[] }): Property<T>;
    }

    export const Property: PropertyAPI;

    export interface ScriptConfiguration {
        id: string;
        name?: string;
        updateRate?: number;
        timeout?: number;
    }

    export interface ScriptAPI {
        readonly id: string;
        readonly name: string;
        readonly state: Record<string, unknown>;
        readonly storage: Record<string, unknown>;
        configure(configuration: ScriptConfiguration): void;
        reload(): void;
    }

    export const Script: ScriptAPI;

    export interface SystemUpdateEvent {
        readonly time: number;
        readonly deltaTime: number;
    }

    export interface SystemDisposeEvent {
        readonly reason: DisposeReason;
    }

    export interface SystemAPI {
        readonly time: number;
        on(event: "initialize", callback: () => void | Promise<void>): Subscription;
        on(event: "update", callback: (event: SystemUpdateEvent) => void | Promise<void>): Subscription;
        on(event: "dispose", callback: (event: SystemDisposeEvent) => void | Promise<void>): Subscription;
        sleep(seconds: number): Promise<void>;
    }

    export const System: SystemAPI;

    export interface RuntimeAPI {
        currentShader(): string | undefined;
        previousShader(): string | undefined;
        setShader(id: string, transitionSeconds?: number): boolean;
        setShaderPreset(index: number, transitionSeconds?: number): boolean;
        setMaterial(id: string, component: number, value: number): boolean;
        setBrightness(value: number): boolean;
        setFramebufferEnabled(enabled: boolean): boolean;
        setBaseColorMode(mode: number): boolean;
        clearShader(): boolean;
        clear(): boolean;
    }

    export const Runtime: RuntimeAPI;

    export interface Instruction {
        readonly address: Address;
        readonly size: number;
        readonly text: string;
        readonly bytes: string;
    }

    export interface DisassemblyAPI {
        decode(process: Process, address: Address | number, count?: number): Instruction[];
    }

    export const Disassembly: DisassemblyAPI;

    export interface MemoryAPI {
        readBytes(process: Process, address: Address | number, length: number): Uint8Array;
        writeBytes(process: Process, address: Address | number, bytes: ArrayLike<number> | string): void;
    }

    export const Memory: MemoryAPI;

    export interface KeyboardAPI {
        keyDown(key: InputKey): boolean;
        shortcut(key: InputKey, modifiers?: { ctrl?: boolean; alt?: boolean; shift?: boolean }): boolean;
        readonly capsLock: boolean;
        readonly scrollLock: boolean;
    }

    export const Keyboard: KeyboardAPI;

    export interface GlobalEvent {
        readonly type: string;
        readonly time: number;
        readonly [key: string]: unknown;
    }

    export interface EventsAPI {
        on(type: string, callback: (event: GlobalEvent) => void): Subscription;
        emit(type: string, data?: unknown): void;
    }

    export const Events: EventsAPI;
}
)TS";
        return Declarations;
    }

    std::filesystem::path runtimeQuickJSTypeDeclarationsPath() { return runtimeQuickJSScriptDirectory() / "quartz-client.d.ts"; }

    bool runtimeSaveQuickJSTypeDeclarations(std::string& error)
    {
        const auto path = runtimeQuickJSTypeDeclarationsPath();
        std::error_code ec;
        std::filesystem::create_directories(path.parent_path(), ec);
        std::ofstream file(path, std::ios::binary | std::ios::trunc);
        if (!file) { error = "could not open " + path.string(); return false; }
        const auto declarations = runtimeQuickJSTypeDeclarations();
        file.write(declarations.data(), static_cast<std::streamsize>(declarations.size()));
        if (!file) { error = "could not write " + path.string(); return false; }
        file.close();
        if (!file) { error = "could not close " + path.string(); return false; }
        const auto oldPath = path.parent_path().parent_path() / "quartz-runtime.d.ts";
        std::filesystem::remove(oldPath, ec);
        error.clear();
        return true;
    }
}
