#include "QuickJSInternal.hpp"
#include "quartz/client/Functions.hpp"
#include "quartz/client/runtime/QuickJS.hpp"
#include "quartz/client/runtime/RuntimeBindingEngine.hpp"
#include "quartz/client/shader/ShaderFramebuffer.hpp"
#include <quickjs.h>
#include <algorithm>
#include <chrono>
#include <fstream>
#include <memory>
#include <unordered_map>

namespace quartz::client
{
    namespace
    {
        constexpr std::size_t WorkspaceMemoryLimit=64ULL*1024ULL*1024ULL, WorkspaceStackLimit=512ULL*1024ULL;
        constexpr double MaximumSafeInteger=9007199254740991.0;
        std::uint64_t hashText(const std::string_view text) noexcept { std::uint64_t h=14695981039346656037ULL;for(const unsigned char c:text){h^=c;h*=1099511628211ULL;}return h; }
        std::string exceptionText(JSContext* ctx){JSValue ex=JS_GetException(ctx);std::string out="QuickJS exception";if(const char*t=JS_ToCString(ctx,ex)){out=t;JS_FreeCString(ctx,t);}if(JS_IsObject(ex)){JSValue stack=JS_GetPropertyStr(ctx,ex,"stack");if(const char*t=JS_ToCString(ctx,stack)){if(*t){out+='\n';out+=t;}JS_FreeCString(ctx,t);}JS_FreeValue(ctx,stack);}JS_FreeValue(ctx,ex);return out;}
        struct Instance:RuntimeQuickJSContext
        {
            JSContext* Context=nullptr;JSValue Function=JS_UNDEFINED,Api=JS_UNDEFINED;std::uint64_t SourceHash=0;std::filesystem::path MainPath,CurrentDirectory;std::unordered_map<std::string,std::filesystem::file_time_type> DependencyTimes;std::unordered_map<std::string,JSValue> Modules;
            ~Instance(){if(!Context)return;for(auto&[_,v]:Modules)JS_FreeValue(Context,v);JS_FreeValue(Context,Function);JS_FreeValue(Context,Api);JS_FreeContext(Context);}
        };
        struct Workspace
        {
            JSRuntime* Runtime=nullptr;RuntimeQuickJSDeadline Execution{};std::unordered_map<std::uint64_t,std::unique_ptr<Instance>> Instances;
            Workspace(){Runtime=JS_NewRuntime();if(Runtime){JS_SetMemoryLimit(Runtime,WorkspaceMemoryLimit);JS_SetMaxStackSize(Runtime,WorkspaceStackLimit);JS_SetRuntimeOpaque(Runtime,this);JS_SetInterruptHandler(Runtime,[](JSRuntime*,void* opaque){auto*self=static_cast<Workspace*>(opaque);if(!self||!self->Execution.Active||std::chrono::steady_clock::now()<self->Execution.Deadline)return 0;self->Execution.Interrupted=true;return 1;},this);}}
            ~Workspace(){Instances.clear();if(Runtime)JS_FreeRuntime(Runtime);}
            void begin(float ms){Execution.Interrupted=false;Execution.Active=true;Execution.Deadline=std::chrono::steady_clock::now()+std::chrono::duration_cast<std::chrono::steady_clock::duration>(std::chrono::duration<double,std::milli>(std::clamp(ms,0.1f,100.0f)));}void end(){Execution.Active=false;}
        };
        Workspace& workspace(){static Workspace w;return w;}
        RuntimeBinding* resolveBinding(JSContext*ctx,JSValueConst v){auto*s=static_cast<RuntimeQuickJSContext*>(JS_GetContextOpaque(ctx));if(!s||!s->Engine)return nullptr;if(JS_IsNumber(v)||JS_IsBigInt(ctx,v)){std::int64_t id=0;if(JS_ToInt64Ext(ctx,&id,v)<0||id<=0)return nullptr;return s->Engine->findBinding(static_cast<std::uint64_t>(id));}const char*n=JS_ToCString(ctx,v);if(!n)return nullptr;auto*r=s->Engine->findBindingByName(n);JS_FreeCString(ctx,n);return r;}
        RuntimeControlRule* resolveControl(JSContext*ctx,JSValueConst v){auto*s=static_cast<RuntimeQuickJSContext*>(JS_GetContextOpaque(ctx));if(!s||!s->Engine)return nullptr;if(JS_IsNumber(v)||JS_IsBigInt(ctx,v)){std::int64_t id=0;if(JS_ToInt64Ext(ctx,&id,v)<0||id<=0)return nullptr;return s->Engine->findControl(static_cast<std::uint64_t>(id));}const char*n=JS_ToCString(ctx,v);if(!n)return nullptr;auto*r=s->Engine->findControlByName(n);JS_FreeCString(ctx,n);return r;}
        RuntimeValueBankEntry* resolveBank(JSContext*ctx,JSValueConst v){auto*s=static_cast<RuntimeQuickJSContext*>(JS_GetContextOpaque(ctx));if(!s||!s->Engine)return nullptr;if(JS_IsNumber(v)||JS_IsBigInt(ctx,v)){std::int64_t id=0;if(JS_ToInt64Ext(ctx,&id,v)<0||id<=0)return nullptr;return s->Engine->findBankValue(static_cast<std::uint64_t>(id));}const char*n=JS_ToCString(ctx,v);if(!n)return nullptr;auto*r=s->Engine->findBankValueByName(n);JS_FreeCString(ctx,n);return r;}
        JSValue jsBinding(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*b=argc?resolveBinding(ctx,argv[0]):nullptr;return b&&b->Enabled&&b->HasValue?JS_NewFloat64(ctx,b->Value):JS_UNDEFINED;}
        JSValue jsRaw(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*b=argc?resolveBinding(ctx,argv[0]):nullptr;return b&&b->Enabled&&b->HasValue?JS_NewFloat64(ctx,b->RawValue):JS_UNDEFINED;}
        JSValue jsText(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*b=argc?resolveBinding(ctx,argv[0]):nullptr;return b&&b->Enabled&&b->HasString?JS_NewString(ctx,b->StringValue.c_str()):JS_UNDEFINED;}
        JSValue jsAddress(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*b=argc?resolveBinding(ctx,argv[0]):nullptr;return b&&b->Enabled&&b->HasAddress?JS_NewBigUint64(ctx,b->AddressValue):JS_UNDEFINED;}
        JSValue jsBank(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*v=argc?resolveBank(ctx,argv[0]):nullptr;if(!v||!v->Enabled||!v->HasValue)return JS_UNDEFINED;switch(v->Type){case RuntimeBankValueType::Number:return JS_NewFloat64(ctx,v->Number);case RuntimeBankValueType::Integer:return std::abs(static_cast<double>(v->Integer))<=MaximumSafeInteger?JS_NewFloat64(ctx,static_cast<double>(v->Integer)):JS_NewBigInt64(ctx,v->Integer);case RuntimeBankValueType::Boolean:return JS_NewBool(ctx,v->Boolean);case RuntimeBankValueType::String:return JS_NewString(ctx,v->String);case RuntimeBankValueType::Address:return v->Address?JS_NewBigUint64(ctx,v->Address):JS_UNDEFINED;}return JS_UNDEFINED;}
        JSValue jsControl(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*c=argc?resolveControl(ctx,argv[0]):nullptr;return c&&c->Enabled&&c->RuntimeEnabled?JS_NewBool(ctx,c->ConditionActive):JS_UNDEFINED;}
        JSValue jsTriggered(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*c=argc?resolveControl(ctx,argv[0]):nullptr;return c&&c->Enabled&&c->RuntimeEnabled?JS_NewBool(ctx,c->TriggeredThisFrame):JS_UNDEFINED;}
        JSValue jsLog(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv){auto*s=static_cast<RuntimeQuickJSContext*>(JS_GetContextOpaque(ctx));if(!s||!s->Script)return JS_UNDEFINED;std::string text;for(int i=0;i<argc;++i){const char*v=JS_ToCString(ctx,argv[i]);if(!v)return JS_EXCEPTION;if(!text.empty())text.push_back(' ');if(text.size()<2048)text.append(v,std::min<std::size_t>(std::strlen(v),2048-text.size()));JS_FreeCString(ctx,v);}s->Script->LastLog=std::move(text);return JS_UNDEFINED;}
        bool loadFile(const std::filesystem::path& path,std::string& text){std::ifstream file(path,std::ios::binary);if(!file)return false;text.assign(std::istreambuf_iterator<char>(file),{});return static_cast<bool>(file)||file.eof();}
        std::filesystem::file_time_type fileTime(const std::filesystem::path& path){std::error_code ec;const auto t=std::filesystem::last_write_time(path,ec);return ec?std::filesystem::file_time_type::min():t;}
        JSValue jsImport(JSContext*ctx,JSValueConst,int argc,JSValueConst*argv)
        {
            if(argc<1)return JS_ThrowTypeError(ctx,"q.import(path): path required");auto*base=static_cast<RuntimeQuickJSContext*>(JS_GetContextOpaque(ctx));auto*instance=static_cast<Instance*>(base);const char*raw=JS_ToCString(ctx,argv[0]);if(!raw)return JS_EXCEPTION;std::filesystem::path requested(raw);JS_FreeCString(ctx,raw);std::filesystem::path path=requested.is_absolute()?requested:instance->CurrentDirectory/requested;std::error_code ec;path=std::filesystem::weakly_canonical(path,ec);if(ec)path=std::filesystem::absolute(path,ec);if(path.extension()!=".js"&&path.extension()!=".mjs")return JS_ThrowTypeError(ctx,"q.import only accepts .js/.mjs files");const std::string key=path.string();if(const auto it=instance->Modules.find(key);it!=instance->Modules.end())return JS_DupValue(ctx,it->second);std::string source;if(!loadFile(path,source))return JS_ThrowReferenceError(ctx,"could not import %s",key.c_str());instance->DependencyTimes[key]=fileTime(path);std::string wrapped="(function(q,exports,module){\n\"use strict\";\n"+source+"\n;return module.exports;\n})";auto&w=workspace();w.begin(instance->Script?instance->Script->TimeoutMs:4.0f);JSValue fn=JS_Eval(ctx,wrapped.c_str(),wrapped.size(),key.c_str(),JS_EVAL_TYPE_GLOBAL|JS_EVAL_FLAG_STRICT);w.end();if(JS_IsException(fn))return fn;JSValue exports=JS_NewObject(ctx),module=JS_NewObject(ctx);JS_SetPropertyStr(ctx,module,"exports",JS_DupValue(ctx,exports));JSValue args[3]{JS_DupValue(ctx,instance->Api),JS_DupValue(ctx,exports),JS_DupValue(ctx,module)};const auto old=instance->CurrentDirectory;instance->CurrentDirectory=path.parent_path();w.begin(instance->Script?instance->Script->TimeoutMs:4.0f);JSValue result=JS_Call(ctx,fn,JS_UNDEFINED,3,args);w.end();instance->CurrentDirectory=old;for(auto&a:args)JS_FreeValue(ctx,a);JS_FreeValue(ctx,fn);JS_FreeValue(ctx,exports);JS_FreeValue(ctx,module);if(JS_IsException(result))return result;instance->Modules.emplace(key,JS_DupValue(ctx,result));return result;
        }
        Instance* createInstance(RuntimeBindingEngine& engine,RuntimeScript& script,const RuntimeSignalContext& signal,ShaderFramebuffer& shader,RuntimeControlOutput& output)
        {
            auto&w=workspace();if(!w.Runtime)return nullptr;auto[it,inserted]=w.Instances.try_emplace(script.Id);if(!inserted)return it->second.get();auto instance=std::make_unique<Instance>();instance->Execution=&w.Execution;instance->Engine=&engine;instance->Script=&script;instance->SignalContext=&signal;instance->Shader=&shader;instance->Output=&output;instance->AllowGraphMutation=true;instance->Context=JS_NewContext(w.Runtime);if(!instance->Context){w.Instances.erase(it);return nullptr;}JS_SetContextOpaque(instance->Context,static_cast<RuntimeQuickJSContext*>(instance.get()));instance->Api=JS_NewObject(instance->Context);JS_SetPropertyStr(instance->Context,instance->Api,"binding",JS_NewCFunction(instance->Context,jsBinding,"binding",1));JS_SetPropertyStr(instance->Context,instance->Api,"raw",JS_NewCFunction(instance->Context,jsRaw,"raw",1));JS_SetPropertyStr(instance->Context,instance->Api,"text",JS_NewCFunction(instance->Context,jsText,"text",1));JS_SetPropertyStr(instance->Context,instance->Api,"address",JS_NewCFunction(instance->Context,jsAddress,"address",1));JS_SetPropertyStr(instance->Context,instance->Api,"bank",JS_NewCFunction(instance->Context,jsBank,"bank",1));JS_SetPropertyStr(instance->Context,instance->Api,"control",JS_NewCFunction(instance->Context,jsControl,"control",1));JS_SetPropertyStr(instance->Context,instance->Api,"triggered",JS_NewCFunction(instance->Context,jsTriggered,"triggered",1));JS_SetPropertyStr(instance->Context,instance->Api,"log",JS_NewCFunction(instance->Context,jsLog,"log",1));JS_SetPropertyStr(instance->Context,instance->Api,"import",JS_NewCFunction(instance->Context,jsImport,"import",1));runtimeInstallQuickJSLowLevelApi(instance->Context,instance->Api);runtimeInstallQuickJSGraphApi(instance->Context,instance->Api);JS_DefinePropertyValueStr(instance->Context,instance->Api,"state",JS_NewObject(instance->Context),JS_PROP_ENUMERABLE);auto*result=instance.get();it->second=std::move(instance);return result;
        }
        bool dependenciesChanged(const Instance& instance){for(const auto&[path,time]:instance.DependencyTimes)if(fileTime(path)!=time)return true;return false;}
        bool compile(Instance& instance,RuntimeScript& script,const std::string& source,const std::filesystem::path& filename,std::string& error)
        {
            const auto hash=hashText(source);if(instance.SourceHash==hash&&JS_IsFunction(instance.Context,instance.Function))return true;JS_FreeValue(instance.Context,instance.Function);instance.Function=JS_UNDEFINED;instance.SourceHash=hash;for(auto&[_,v]:instance.Modules)JS_FreeValue(instance.Context,v);instance.Modules.clear();instance.DependencyTimes.clear();instance.MainPath=filename;instance.CurrentDirectory=filename.empty()?runtimeQuickJSScriptDirectory():filename.parent_path();std::string wrapped="(function(q){\n\"use strict\";\n"+source+"\n})";auto&w=workspace();w.begin(script.TimeoutMs);JSValue fn=JS_Eval(instance.Context,wrapped.c_str(),wrapped.size(),filename.empty()?"quartz-workspace.js":filename.string().c_str(),JS_EVAL_TYPE_GLOBAL|JS_EVAL_FLAG_STRICT);w.end();if(JS_IsException(fn)){if(w.Execution.Interrupted){JSValue ex=JS_GetException(instance.Context);JS_FreeValue(instance.Context,ex);++script.TimeoutCount;error="QuickJS compile timed out";}else error=exceptionText(instance.Context);return false;}instance.Function=fn;++script.CompileCount;return true;
        }
        bool evaluate(RuntimeBindingEngine&engine,RuntimeScript&script,const RuntimeSignalContext&signal,ShaderFramebuffer&shader,RuntimeControlOutput&output)
        {
            auto&w=workspace();const bool watchExternal=engine.scriptSettings().ExternalHotReload&&script.HotReload;auto existing=w.Instances.find(script.Id);if(existing!=w.Instances.end()&&watchExternal&&dependenciesChanged(*existing->second)){w.Instances.erase(existing);++script.ReloadCount;}
            bool reuseExternal=false;std::string source;std::filesystem::path filename;if(script.External){filename=script.Path;if(filename.is_relative())filename=runtimeQuickJSScriptDirectory()/filename;existing=w.Instances.find(script.Id);reuseExternal=existing!=w.Instances.end()&&!watchExternal&&JS_IsFunction(existing->second->Context,existing->second->Function);if(!reuseExternal&&!loadFile(filename,source)){script.Status="could not read external script: "+filename.string();return false;}}else source=script.Source;
            Instance*instance=createInstance(engine,script,signal,shader,output);if(!instance){script.Status="could not create QuickJS workspace context";return false;}instance->Engine=&engine;instance->Script=&script;instance->SignalContext=&signal;instance->Shader=&shader;instance->Output=&output;std::string error;if(!reuseExternal&&!compile(*instance,script,source,filename,error)){script.Status=std::move(error);return false;}JS_SetPropertyStr(instance->Context,instance->Api,"time",JS_NewFloat64(instance->Context,signal.Time));JS_SetPropertyStr(instance->Context,instance->Api,"deltaTime",JS_NewFloat64(instance->Context,signal.DeltaTime));JS_SetPropertyStr(instance->Context,instance->Api,"id",JS_NewBigUint64(instance->Context,script.Id));JS_SetPropertyStr(instance->Context,instance->Api,"name",JS_NewString(instance->Context,script.Name));JSValue arg=JS_DupValue(instance->Context,instance->Api);const auto started=std::chrono::steady_clock::now();w.begin(script.TimeoutMs);JSValue result=JS_Call(instance->Context,instance->Function,JS_UNDEFINED,1,&arg);w.end();script.LastMilliseconds=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();++script.RunCount;JS_FreeValue(instance->Context,arg);if(JS_IsException(result)){if(w.Execution.Interrupted){JSValue ex=JS_GetException(instance->Context);JS_FreeValue(instance->Context,ex);++script.TimeoutCount;script.Status="execution timed out after "+std::to_string(script.TimeoutMs)+" ms";}else script.Status=exceptionText(instance->Context);return false;}JS_FreeValue(instance->Context,result);script.Dependencies.clear();for(const auto&[path,_]:instance->DependencyTimes)script.Dependencies.push_back(path);script.Status="running";return true;
        }
    }

    RuntimeControlOutput runtimeEvaluateWorkspaceScripts(RuntimeBindingEngine& engine,const RuntimeSignalContext& context,ShaderFramebuffer& shader)
    {
        RuntimeControlOutput output;for(auto&script:engine.scripts()){if(!script.Enabled||context.Time<script.NextUpdate)continue;const float hz=std::clamp(script.UpdateHz,0.5f,500.0f);script.NextUpdate=context.Time+1.0/hz;evaluate(engine,script,context,shader,output);}return output;
    }
    void runtimeResetWorkspaceScript(const std::uint64_t id) noexcept {workspace().Instances.erase(id);if(workspace().Runtime)JS_RunGC(workspace().Runtime);}
    void runtimeReloadAllWorkspaceScripts() noexcept {auto&w=workspace();for(auto&[_,instance]:w.Instances)if(instance&&instance->Script)++instance->Script->ReloadCount;w.Instances.clear();if(w.Runtime)JS_RunGC(w.Runtime);}
    std::filesystem::path runtimeQuickJSScriptDirectory(){return settingsPath().parent_path()/"scripts";}
}
