#include "quartz/client/ui/I18n.hpp"
#include "quartz/client/Functions.hpp"
#include <algorithm>
#include <array>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <imgui.h>
#include <string>

namespace quartz::client::ui::i18n
{
    namespace
    {
        struct Entry { std::string_view Key; const char* English; const char* Portuguese; };
        constexpr auto Catalog = std::to_array<Entry>({
            {"nav.section.visual","VISUAL","VISUAL"},{"nav.section.scripting","SCRIPTING","SCRIPTS"},{"nav.section.reverseEngineering","REVERSE ENGINEERING","ENGENHARIA REVERSA"},{"nav.section.device","DEVICE","DISPOSITIVO"},{"nav.section.diagnostics","DIAGNOSTICS","DIAGNÓSTICOS"},{"nav.section.other","OTHER","OUTROS"},
            {"nav.visualizer","Visualizer","Visualizador"},{"nav.shaders","Shaders","Sombreadores"},{"nav.spectrum","Spectrum","Espectro"},{"nav.audio","Audio","Áudio"},{"nav.rgb","RGB","RGB"},{"nav.javascript","Scripts","Scripts"},{"nav.profiles","Profiles","Perfis"},{"nav.native","Workspace","Área de Trabalho"},{"nav.memory-scanner","Memory Scanner","Scanner de Memória"},{"nav.memory-watch","Memory Watch","Monitor de Memória"},{"nav.device","Device","Dispositivo"},{"nav.input","Input","Entrada"},{"nav.usb","USB","USB"},{"nav.firmware","Firmware","Firmware"},{"nav.performance","Performance","Desempenho"},{"nav.matrix-timing","Matrix Timing","Timing da Matriz"},{"nav.qrpc","QRPC","QRPC"},{"nav.timeline","Timeline","Linha do Tempo"},

            {"header.byline","Made by Raony Reis, not affiliated with Redragon","Feito por Raony Reis, sem afiliação com a Redragon"},{"header.keyboard","Keyboard","Teclado"},{"header.appearance","Appearance","Aparência"},{"header.configuration","Configuration","Configuração"},{"header.theme","Theme","Tema"},{"header.terminate","Terminate","Encerrar"},{"header.terminateTooltip","Exit Quartz completely. The normal window close button only hides the window.","Fecha o Quartz completamente. O botão normal de fechar apenas oculta a janela."},

            {"appearance.theme","Theme","Tema"},{"theme.quartzCyan","Quartz Cyan","Quartz Ciano"},{"theme.graphite","Graphite","Grafite"},{"theme.oceanBlue","Ocean Blue","Azul Oceano"},{"theme.emerald","Emerald","Esmeralda"},{"theme.devilukePink","Deviluke Pink","Deviluke Rosa"},{"theme.kurosakiPink","Kurosaki Pink","Kurosaki Rosa"},{"theme.yamiGolden","Yami Golden","Yami Dourado"},{"theme.kirisakiPurple","Kirisaki Purple","Kirisaki Roxo"},
            {"appearance.language","Language","Idioma"},{"appearance.cornerRounding","Corner rounding","Cantos arredondados"},{"appearance.silhouetteOpacity","Silhouette opacity","Opacidade da silhueta"},{"appearance.silhouetteOpacityTooltip","Global multiplier for themed background silhouettes. 100% keeps the hand-tuned per-theme opacity; 0% hides them and values above 100% make them more visible.","Multiplicador global das silhuetas de fundo dos temas. 100% mantém a opacidade ajustada de cada tema; 0% oculta as silhuetas e valores acima de 100% as deixam mais visíveis."},{"appearance.suspicious","Enable suspicious color themes","Ativar temas de cores suspeitos"},{"appearance.suspiciousTooltip","Unlocks Deviluke Pink, Kurosaki Pink, Yami Golden and Kirisaki Purple.","Libera Deviluke Rosa, Kurosaki Rosa, Yami Dourado e Kirisaki Roxo."},{"appearance.suspiciousTitle","Suspicious color themes","Temas de cores suspeitos"},{"appearance.suspiciousWarning","These themes are intentionally a little questionable: louder colors, anime silhouettes, and absolutely zero attempt to look corporate. Nothing here changes firmware behavior or unlocks anything dangerous; this only changes Quartz's appearance. If you're okay with your reverse-engineering tool looking slightly less employable, carry on.","Esses temas são intencionalmente meio suspeitos: cores mais chamativas, silhuetas de anime e zero esforço para parecer software corporativo. Nada aqui muda o comportamento do firmware nem libera nada perigoso; isso só altera a aparência do Quartz. Se você aceita que sua ferramenta de engenharia reversa fique um pouco menos empregável, manda ver."},{"appearance.suspiciousEnable","Enable questionable colors","Ativar cores questionáveis"},{"appearance.suspiciousCancel","Keep Quartz respectable","Manter o Quartz respeitável"},{"appearance.globalBrightness","Global brightness","Brilho global"},{"appearance.previewInterpolation","Preview interpolation","Interpolação da prévia"},{"appearance.previewInterpolationTooltip","Preview-only spatial color mixing. It never changes framebuffer data sent over USB.","Mistura espacial de cores apenas na prévia. Nunca altera o framebuffer enviado por USB."},{"appearance.reset","Reset appearance","Redefinir aparência"},{"keyboardPreview.title","Keyboard Preview","Prévia do Teclado"},

            {"configuration.patternScanning","Pattern scanning","Escaneamento de padrões"},{"configuration.signatureScanChunk","Signature scan read chunk (bytes)","Bloco de leitura do scan de assinatura (bytes)"},{"configuration.signatureScanChunkTooltip","Maximum target-process memory copied per libhat-backed signature scan chunk. Quartz clamps this to 64 KiB–64 MiB and aligns it to 8 bytes. Larger chunks reduce process-memory read overhead, but use more temporary memory and make cancellation less granular.","Máximo de memória do processo alvo copiada por bloco de scan de assinatura usando libhat. O Quartz limita entre 64 KiB e 64 MiB e alinha o valor em 8 bytes. Blocos maiores reduzem o overhead das leituras de memória, mas usam mais memória temporária e deixam o cancelamento menos granular."},{"configuration.signatureScanChunkValue","Current: %.2f MiB (%zu bytes), aligned to %zu bytes","Atual: %.2f MiB (%zu bytes), alinhado em %zu bytes"},{"configuration.signatureScanChunkTradeoff","4 MiB is the default. libhat scans the supplied span directly with its selected vectorized backend; the practical tradeoff here is target-memory read overhead versus temporary buffer size and cancellation latency, not a small-buffer limit inside libhat.","4 MiB é o padrão. O libhat varre diretamente o intervalo fornecido usando o backend vetorizado selecionado; o compromisso prático aqui é overhead das leituras da memória alvo contra tamanho do buffer temporário e latência de cancelamento, não um limite de buffer pequeno dentro do libhat."},{"configuration.newScansOnly","Changes apply to newly started scans; running scans keep the chunk size they started with.","As alterações se aplicam a novos scans; scans em andamento mantêm o tamanho de bloco com que foram iniciados."},{"configuration.reset","Reset configuration","Redefinir configuração"},
            {"configuration.disassembler","Disassembler","Desmontador"},{"configuration.disassemblerDescription","Slow refresh defaults keep process-memory reads out of the hot UI path. Set a rate to 0 Hz to disable automatic refresh.","As taxas baixas padrão mantêm leituras da memória do processo fora do caminho quente da UI. Use 0 Hz para desativar a atualização automática."},{"configuration.disassemblyRefresh","Disassembly refresh","Atualização da desmontagem"},{"configuration.rawRefresh","Raw bytes refresh","Atualização dos bytes brutos"},{"configuration.functionHeuristics","Background function heuristics","Heurísticas de função em segundo plano"},{"configuration.functionHeuristicsTooltip","Runs low-priority local function-boundary analysis on Quartz's shared thread pool. The disassembler never waits for it.","Executa análise local de limites de função com baixa prioridade no pool de threads compartilhado do Quartz. O desmontador nunca espera por ela."},{"configuration.functionWindow","Function analysis window","Janela de análise de funções"},{"configuration.functionWindowHint","Local window around the current disassembly address. It is clamped and page-aligned when saved.","Janela local ao redor do endereço atual da desmontagem. O valor é limitado e alinhado à página ao salvar."},
            {"configuration.assemblerTweaks","Assembler Tweaks","Ajustes do Montador"},{"configuration.assemblerDescription","Controls how in-place patches are prepared. Quartz always previews the final byte span before a process write.","Controla como patches no local são preparados. O Quartz sempre mostra a prévia do intervalo final de bytes antes de escrever no processo."},{"configuration.fillNops","Fill remaining bytes with NOPs","Preencher bytes restantes com NOPs"},{"configuration.wholeInstructions","Keep selections on whole instructions","Manter seleções em instruções inteiras"},{"configuration.consumeFollowing","Allow patches to consume following instructions","Permitir que patches consumam instruções seguintes"},{"configuration.consumeFollowingTooltip","If assembled code is larger than the selected span, Quartz may extend the patch over complete following instructions. Disabled by default.","Se o código montado for maior que o intervalo selecionado, o Quartz pode estender o patch sobre instruções seguintes completas. Desativado por padrão."},{"configuration.verifyBeforeWrite","Verify original bytes before writing","Verificar bytes originais antes de escrever"},{"configuration.requireConfirmation","Require write confirmation","Exigir confirmação antes de escrever"},{"configuration.redisassemble","Re-disassemble immediately after patch","Desmontar novamente imediatamente após o patch"},{"configuration.keepOriginal","Keep original bytes for Restore","Manter bytes originais para Restaurar"},

            {"common.refresh","Refresh","Atualizar"},{"common.refreshProcesses","Refresh processes","Atualizar processos"},{"common.process","Process","Processo"},{"common.selectProcess","<select process>","<selecionar processo>"},{"common.processSearchHint","Find PID, process name, title, executable path or command line...","Buscar PID, nome do processo, título, executável ou linha de comando..."},{"common.noProcessMatches","No process matches the filter.","Nenhum processo corresponde ao filtro."},{"common.processLinked","Linked","Vinculado"},{"common.processLocal","Local","Local"},{"common.processLinkTooltip","Linked selectors share one process across the reverse-engineering tools. Switch this selector to Local to keep an independent process.","Seletores vinculados compartilham um processo entre as ferramentas de engenharia reversa. Mude este seletor para Local para manter um processo independente."},{"common.copy","Copy","Copiar"},{"common.cancel","Cancel","Cancelar"},{"common.close","Close","Fechar"},{"common.reset","Reset","Redefinir"},{"common.select","Select","Selecionar"},{"common.open","Open","Abrir"},{"common.edit","Edit...","Editar..."},{"common.connected","connected","conectado"},{"common.disconnected","disconnected","desconectado"},{"common.on","on","ligado"},{"common.off","off","desligado"},{"common.enabled","Enabled","Ativado"},{"common.disabled","Disabled","Desativado"},{"common.status","Status","Status"},{"common.clear","Clear","Limpar"},{"common.copyAll","Copy all","Copiar tudo"},

            {"visualizer.description","Live output. Detailed spectrum/audio tuning, shader management and RGB diagnostics live on their dedicated pages.","Saída ao vivo. Ajustes detalhados de espectro/áudio, gerenciamento de sombreadores e diagnósticos RGB ficam em suas páginas dedicadas."},{"visualizer.output","Output","Saída"},{"visualizer.enabled","Enabled","Ativado"},{"visualizer.sendFramebuffer","Send framebuffer","Enviar framebuffer"},{"visualizer.frameRate","Frame rate","Taxa de quadros"},{"visualizer.rgbWave","RGB wave","Onda RGB"},{"visualizer.solid","Solid","Sólido"},{"visualizer.shader","Shader","Sombreador"},{"visualizer.outputMode","Output mode","Modo de saída"},{"visualizer.waveSpeed","Wave speed","Velocidade da onda"},{"visualizer.solidColor","Solid color","Cor sólida"},{"visualizer.openShaders","Shaders...","Sombreadores..."},{"visualizer.openSpectrum","Spectrum...","Espectro..."},{"visualizer.openAudio","Audio...","Áudio..."},{"visualizer.openRgb","RGB diagnostics...","Diagnósticos RGB..."},{"visualizer.keyboardPreview","Keyboard preview","Prévia do teclado"},{"visualizer.frameStats","Frames sent %llu   dropped %llu   USB %s","Quadros enviados %llu   perdidos %llu   USB %s"},{"visualizer.shaderName","Shader: %s","Sombreador: %s"},{"visualizer.blackOut","Black out","Apagar LEDs"},

            {"spectrum.analysisGraph","Analysis graph","Gráfico de análise"},{"spectrum.mappedGraph","Mapped graph","Gráfico mapeado"},{"spectrum.framebufferPreview","Framebuffer preview","Prévia do framebuffer"},{"spectrum.fftAnalysis","FFT / log-frequency analysis","Análise FFT / frequência logarítmica"},{"spectrum.mappedColumns","Mapped 16 columns","16 colunas mapeadas"},{"spectrum.smoothedOutput","Smoothed output","Saída suavizada"},{"spectrum.keyboardFramebuffer","Keyboard framebuffer","Framebuffer do teclado"},{"spectrum.previewInterpolation","Preview interpolation %.0f%% (visual only)","Interpolação da prévia %.0f%% (somente visual)"},

            {"shaders.description","Shader catalog, external source files, hot reload, compilation and reflected material parameters live here. Opening a file keeps Quartz bound to it; importing copies a fragment shader into the Quartz catalog.","Catálogo de sombreadores, arquivos externos, recarga automática, compilação e parâmetros de material refletidos ficam aqui. Abrir um arquivo mantém o Quartz vinculado a ele; importar copia um sombreador de fragmento para o catálogo do Quartz."},{"shaders.current","Current shader","Sombreador atual"},{"shaders.catalog","Catalog","Catálogo"},{"shaders.customExternal","Custom / external","Personalizado / externo"},{"shaders.refreshCatalog","Refresh catalog","Atualizar catálogo"},{"shaders.compileCurrent","Compile current","Compilar atual"},{"shaders.saveDefaults","Save as Quartz defaults","Salvar como padrão do Quartz"},{"shaders.restoreDefault","Restore default","Restaurar padrão"},{"shaders.externalFiles","External files","Arquivos externos"},{"shaders.vertexFile","Vertex file","Arquivo de vértices"},{"shaders.fragmentFile","Fragment file","Arquivo de fragmento"},{"shaders.importCatalog","Import to catalog","Importar para o catálogo"},{"shaders.hotReload","Hot reload external changes","Recarregar alterações externas"},{"shaders.hotReloadHint","200 ms debounce/poll; external edits compile automatically","debounce/poll de 200 ms; edições externas compilam automaticamente"},{"shaders.renderSurface","Render surface","Superfície de renderização"},{"shaders.framebufferSize","Framebuffer size","Tamanho do framebuffer"},{"shaders.regenerate","Regenerate","Regenerar"},{"shaders.downsample","Downsample","Redução de amostragem"},{"shaders.crossfade","Crossfade","Transição"},{"shaders.recompileChange","Recompile on editor text change","Recompilar ao alterar o texto do editor"},{"shaders.keyUniforms","Key-state uniforms","Uniformes de estado das teclas"},{"shaders.capsColor","Caps Lock fixed color","Cor fixa do Caps Lock"},{"shaders.scrollColor","Scroll Lock fixed color","Cor fixa do Scroll Lock"},{"shaders.materialParameters","Material parameters","Parâmetros de material"},

            {"re.workspaceDescription","Native reverse-engineering workspace. Memory, disassembly, watches and signatures share addresses directly so you can move through a process without copy/pasting hexadecimal values between unrelated tools.","Área de trabalho de engenharia reversa nativa. Memória, desmontagem, monitores e assinaturas compartilham endereços diretamente para navegar pelo processo sem copiar e colar valores hexadecimais entre ferramentas."},{"re.memoryDisassembly","Memory / disassembly","Memória / desmontagem"},{"re.memoryScanner","Memory Scanner...","Scanner de Memória..."},{"re.memoryWatch","Memory Watch...","Monitor de Memória..."},{"re.signatureFromAddress","Signature from address","Assinatura do endereço"},{"re.manualWatch","Manual watch","Monitor manual"},{"re.signatures","Signatures","Assinaturas"},{"re.signatureSearch","Search","Buscar"},{"re.objectExperiments","Object experiments","Experimentos com Objetos"},{"re.signatureMaker","Signature Maker","Gerador de Assinatura"},{"re.makeSignature","Make signature","Gerar assinatura"},{"re.copySignature","Copy signature","Copiar assinatura"},{"re.signatureUnique","Unique match","Correspondência única"},{"re.signatureConflict","Conflicting matches","Correspondências conflitantes"},{"re.signatureAddress","Target address","Endereço alvo"},{"re.signatureBytes","Instruction bytes","Bytes das instruções"},{"re.signatureStatus","Status","Status"},{"re.signatureDescription","Build a signature from decoded instructions. Relocation-sensitive operands are wildcarded automatically and libhat extends the pattern until the target is unique.","Gera uma assinatura a partir das instruções decodificadas. Operandos sensíveis a relocação recebem curingas automaticamente e o libhat estende o padrão até o alvo ser único."},{"re.signatureMinimumInstructions","Minimum instructions","Instruções mínimas"},{"re.signatureMaximumInstructions","Maximum instructions","Instruções máximas"},{"re.signatureMatches","Matches","Correspondências"},{"re.inspect","Inspect","Inspecionar"},
            {"re.disassembly","Disassembly","Desmontagem"},{"re.readDisassemble","Read / disassemble","Ler / desmontar"},{"re.synchronizeAddress","Synchronize address","Sincronizar endereço"},{"re.syncedAddress","synced %s","sincronizado %s"},{"re.backTooltip","Back (Ctrl+Z while hovering the disassembler)","Voltar (Ctrl+Z ao passar o mouse sobre o desmontador)"},{"re.forwardTooltip","Forward (Ctrl+Y while hovering the disassembler)","Avançar (Ctrl+Y ao passar o mouse sobre o desmontador)"},{"re.goTo","Go to...","Ir para..."},{"re.goToAddress","Go to address","Ir para endereço"},{"re.go","Go","Ir"},{"re.prefetchHint","The disassembler keeps roughly three viewports loaded and silently recenters the backing window before you reach either edge. Ctrl+click a branch/call target to follow it; G opens Go to.","O desmontador mantém aproximadamente três viewports carregados e recentraliza silenciosamente a janela de memória antes de você chegar às bordas. Ctrl+clique em um alvo de branch/call para segui-lo; G abre Ir para."},{"re.armedNextExecution","armed for next execution","armado para a próxima execução"},{"re.cancelProbe","Cancel execution probe","Cancelar probe de execução"},{"re.lastCapture","Last one-shot capture: %s on TID %d","Última captura única: %s na TID %d"},{"re.armAgain","Arm again","Armar novamente"},{"re.functionAnalysis","function analysis","análise de funções"},{"re.functionAnalysisLive","background / low priority — %zu candidates appear live","segundo plano / baixa prioridade — %zu candidatos aparecem ao vivo"},{"re.functionHints","%s | %zu function hints","%s | %zu indícios de função"},
            {"re.syncHere","Synchronize address here","Sincronizar endereço aqui"},{"re.useInspectorBase","Use as inspector base","Usar como base do inspetor"},{"re.copyModuleAddress","Copy module-relative address","Copiar endereço relativo ao módulo"},{"re.copyAbsoluteAddress","Copy absolute address","Copiar endereço absoluto"},{"re.copyInstruction","Copy instruction line","Copiar linha da instrução"},{"re.createSignatureSelection","Create signature from selection","Criar assinatura da seleção"},{"re.createSignatureHere","Create signature here","Criar assinatura aqui"},{"re.assembleSelection","Assemble / patch selection","Montar / aplicar patch na seleção"},{"re.assembleInstruction","Assemble / patch instruction","Montar / aplicar patch na instrução"},{"re.nopSelection","NOP selection","Aplicar NOP na seleção"},{"re.nopInstruction","NOP instruction","Aplicar NOP na instrução"},{"re.goFunctionStart","Go to function start","Ir para o início da função"},{"re.copyFunctionAddress","Copy function address","Copiar endereço da função"},{"re.functionName","Function name","Nome da função"},{"re.analyzeFunctions","Analyze functions around here","Analisar funções ao redor daqui"},{"re.captureRegisters","Capture registers when executed","Capturar registradores quando executar"},{"re.addBookmark","Add bookmark / marker","Adicionar favorito / marcador"},{"re.bookmark","Bookmark","Favorito"},{"re.tag","Tag","Rótulo"},{"re.color","Color","Cor"},{"re.removeBookmark","Remove bookmark","Remover favorito"},
            {"re.rawBytes","Raw bytes","Bytes brutos"},{"re.rawBytesDescription","16 bytes per row, grouped 8 + 8. Automatic raw refresh %.2f Hz.","16 bytes por linha, agrupados em 8 + 8. Atualização automática dos bytes brutos em %.2f Hz."},{"re.copyByteGroup","Copy 16-byte group","Copiar grupo de 16 bytes"},{"re.registers","Registers","Registradores"},{"re.assembler","Assembler","Montador"},{"re.bookmarks","Bookmarks","Favoritos"},{"re.patchHistory","Patch history","Histórico de patches"},{"re.patchBytes","Patch bytes","Aplicar patch em bytes"},{"re.noBookmarks","No bookmarks for this process yet. Right-click a disassembly instruction to add one.","Ainda não há favoritos para este processo. Clique com o botão direito em uma instrução para adicionar um."},{"re.remove","Remove","Remover"},
            {"re.assemblerEmpty","Right-click an instruction or selection and choose Assemble / patch to open an in-place patch here.","Clique com o botão direito em uma instrução ou seleção e escolha Montar / aplicar patch para abrir um patch no local aqui."},{"re.patchAt","Patch at %s | selected span %zu bytes","Patch em %s | intervalo selecionado de %zu bytes"},{"re.nopMode","NOP mode","Modo NOP"},{"re.encodingPreview","Encoding preview","Prévia da codificação"},{"re.originalBytes","Original: %s","Original: %s"},{"re.patchBytesValue","Patch:    %s","Patch:    %s"},{"re.shortPatchWarning","Replacement is shorter than the selected span; trailing original bytes will remain executable.","A substituição é menor que o intervalo selecionado; os bytes originais restantes continuarão executáveis."},{"re.confirmPatch","Confirm patch","Confirmar patch"},{"re.writePatch","Write patch","Escrever patch"},{"re.rebuildPreview","Rebuild preview","Reconstruir prévia"},{"re.noPatchHistory","No restorable assembler patches in this session.","Nenhum patch restaurável do montador nesta sessão."},{"re.restore","Restore","Restaurar"},{"re.copyAddress","Copy address","Copiar endereço"},{"re.noRegisterCapture","No one-shot execution capture for this process yet. Right-click a disassembly line and choose Capture registers when executed.","Ainda não há captura única de execução para este processo. Clique com o botão direito em uma linha da desmontagem e escolha Capturar registradores quando executar."},{"re.capturedAt","Captured at %s | TID %d | %s register view","Capturado em %s | TID %d | visualização de registradores %s"},{"re.register","Register","Registrador"},{"re.value","Value","Valor"},{"re.copySymbolicAddress","Copy symbolic address","Copiar endereço simbólico"},{"re.copyHex","Copy hexadecimal","Copiar hexadecimal"},{"re.copyDecimal","Copy decimal","Copiar decimal"},{"re.inspectValueAddress","Inspect/disassemble value as address","Inspecionar/desmontar valor como endereço"},{"re.rawPatcherDescription","Editable hexadecimal bytes for the loaded prefetched block. The assembler is safer for instruction patches.","Bytes hexadecimais editáveis do bloco pré-carregado. O montador é mais seguro para patches de instruções."},{"re.writeChanges","Write changes","Escrever alterações"},{"re.confirmWrite","Confirm write","Confirmar escrita"},{"re.cancelWrite","Cancel write","Cancelar escrita"},
            {"re.scannerDescription","Search process memory by value and keep interesting results in a live watch list.","Procure valores na memória do processo e mantenha resultados interessantes em uma lista de monitoramento ao vivo."},{"re.scanResults","Scan results","Resultados do scan"},{"re.watchList","Watch list","Lista de monitoramento"},{"re.freezeRate","Freeze rate","Taxa de congelamento"},{"re.clearWatchList","Clear watch list","Limpar lista de monitoramento"},{"re.address","Address","Endereço"},{"re.type","Type","Tipo"},{"re.previousValue","Previous value","Valor anterior"},{"re.previous","Previous","Anterior"},{"re.freeze","Freeze","Congelar"},{"re.inspectMemory","Inspect memory","Inspecionar memória"},{"re.disassemble","Disassemble","Desmontar"},{"re.watchAccesses","Watch accesses...","Monitorar acessos..."},{"re.addWatchList","Add to watch list","Adicionar à lista de monitoramento"},{"re.inspectCurrentAddress","Inspect current value as address","Inspecionar valor atual como endereço"},{"re.copyCurrentValue","Copy current value","Copiar valor atual"},{"re.copyPreviousValue","Copy previous value","Copiar valor anterior"},{"re.copyAddressValue","Copy address + value","Copiar endereço + valor"},{"re.changeValue","Change value","Alterar valor"},{"re.writeValue","Write value","Escrever valor"},{"re.changeAddress","Change address","Alterar endereço"},{"re.applyAddress","Apply address","Aplicar endereço"},{"re.changeType","Change type","Alterar tipo"},{"re.width","Width","Largura"},{"re.write","Write","Escrever"},{"re.inspectValueAsAddress","Inspect value as address","Inspecionar valor como endereço"},{"re.copyValue","Copy value","Copiar valor"},{"re.removeWatchList","Remove from watch list","Remover da lista de monitoramento"},{"re.derivePattern","Derive byte pattern from address range","Derivar padrão de bytes de um intervalo de endereços"},{"re.derivePatternDescription","Reads [start, end) and optionally wildcards relocation-sensitive operands decoded by Zydis.","Lê [início, fim) e opcionalmente aplica curingas a operandos sensíveis a relocação decodificados pelo Zydis."},{"re.start","Start","Início"},{"re.end","End","Fim"},{"re.wildcardRelocations","Wildcard relocation-sensitive operands","Aplicar curingas em operandos sensíveis a relocação"},{"re.derivedPattern","Derived pattern","Padrão derivado"},{"re.copyPattern","Copy pattern","Copiar padrão"},{"re.createNativeBinding","Create native-address binding","Criar binding de endereço nativo"},
            {"re.manualWatchDescription","Pin an arbitrary process address directly into the scanner watch list without running a value scan first.","Fixe um endereço arbitrário do processo diretamente na lista de monitoramento do scanner sem executar um scan de valor antes."},{"re.addWatch","Add to watch list","Adicionar à lista de monitoramento"},{"re.quickSignatureDescription","Fast first-match hexadecimal signature search using the shared asynchronous libhat scanner. Results can immediately feed the inspector, watch list, hardware watcher or runtime bindings.","Busca rápida da primeira correspondência de assinatura hexadecimal usando o scanner assíncrono compartilhado do libhat. Os resultados podem alimentar imediatamente o inspetor, a lista de monitoramento, o monitor de hardware ou bindings de runtime."},{"re.pattern","Pattern","Padrão"},{"re.executableOnly","Executable mappings only","Somente mapeamentos executáveis"},{"re.searchSignature","Search signature","Buscar assinatura"},{"re.match","Match","Correspondência"},{"re.watchAs","Watch as","Monitorar como"},{"re.createSignatureBinding","Create signature address binding","Criar binding de endereço por assinatura"},
            {"re.objectDescription","Define temporary native object layouts in TypeScript and bind them to a process address.","Defina layouts temporários de objetos nativos em TypeScript e vincule-os a um endereço do processo."},{"re.applyDefinition","Apply definition","Aplicar definição"},{"re.bindAddress","Bind address","Vincular endereço"},{"re.useInspectorAddress","Use inspector address","Usar endereço do inspetor"},{"re.liveRefresh","Live refresh","Atualização ao vivo"},{"re.definition","Definition","Definição"},{"re.field","Field","Campo"},{"re.offset","Offset","Deslocamento"},{"re.raw","Raw bytes","Bytes brutos"},

            {"device.identity","Identity","Identidade"},{"device.product","Product: %s","Produto: %s"},{"device.firmware","Firmware: %s","Firmware: %s"},{"device.packetHeader","Packet header: %zu B   framebuffer payload: %zu B   full frame packet: %zu B","Cabeçalho do pacote: %zu B   payload do framebuffer: %zu B   pacote completo: %zu B"},{"device.logicalFramebuffer","Logical framebuffer: %zux%zu = %zu cells   active RGB area: %zux%zu","Framebuffer lógico: %zux%zu = %zu células   área RGB ativa: %zux%zu"},{"device.sessionOutput","Session / output","Sessão / saída"},{"device.uptimeCpu","Client uptime: %.1f s   App CPU: %.2f%%","Tempo ativo do cliente: %.1f s   CPU do app: %.2f%%"},{"device.txStats","TX frames: %llu   dropped/busy: %llu   RX packets: %llu","Quadros TX: %llu   perdidos/ocupados: %llu   pacotes RX: %llu"},{"device.outputMode","Output mode: %s   target: %d Hz   estimated framebuffer TX: %.1f KiB/s","Modo de saída: %s   alvo: %d Hz   TX estimado do framebuffer: %.1f KiB/s"},{"device.brightness","Brightness: %.0f%%   live-preview interpolation: %.0f%%","Brilho: %.0f%%   interpolação da prévia ao vivo: %.0f%%"},{"device.hostInput","Host input / window","Entrada do host / janela"},{"device.inputDevice","Input device: %s","Dispositivo de entrada: %s"},{"device.locks","Caps Lock: %s   Scroll Lock: %s","Caps Lock: %s   Scroll Lock: %s"},{"device.closeHint","Closing the GLFW window hides it. Ctrl + Alt + Shift + Q restores it globally. Use Terminate in the permanent header to actually exit.","Fechar a janela GLFW apenas a oculta. Ctrl + Alt + Shift + Q restaura globalmente. Use Encerrar no cabeçalho permanente para realmente sair."},{"device.runtimeFiles","Runtime files","Arquivos de runtime"},{"device.settingsFile","Settings: %s","Configurações: %s"},{"device.vertexFile","Vertex shader: %s","Sombreador de vértices: %s"},{"device.fragmentFile","Fragment shader: %s","Sombreador de fragmentos: %s"},{"device.materialFile","Material parameters: %s","Parâmetros de material: %s"},{"device.bindingsFile","Runtime bindings: %s","Bindings de runtime: %s"},

            {"performance.host","Host CPU: %.2f%%   target framebuffer rate: %d Hz   estimated TX: %.1f KiB/s","CPU do host: %.2f%%   taxa alvo do framebuffer: %d Hz   TX estimado: %.1f KiB/s"},{"performance.packets","Packets received: %llu   frames sent: %llu   dropped/busy: %llu","Pacotes recebidos: %llu   quadros enviados: %llu   perdidos/ocupados: %llu"},{"performance.waiting","Waiting for PerformanceResponse...","Aguardando PerformanceResponse..."},{"matrix.waiting","Waiting for MatrixTimingProbeResult...","Aguardando MatrixTimingProbeResult..."},

            {"qrpc.clear","Clear packets","Limpar pacotes"},{"qrpc.resume","Resume live","Retomar ao vivo"},{"qrpc.pausedHint","paused - incoming packets keep being captured","pausado - pacotes recebidos continuam sendo capturados"},{"qrpc.pause","Pause view","Pausar visualização"},{"qrpc.selectHint","selecting a packet pauses the list so it cannot scroll away","selecionar um pacote pausa a lista para ele não desaparecer com a rolagem"},{"qrpc.inspector","QRPC packet inspector","Inspetor de pacotes QRPC"},{"qrpc.dir","Dir","Dir"},{"qrpc.type","Type","Tipo"},{"qrpc.packetId","Packet id","ID do pacote"},{"qrpc.responseFor","Response for","Resposta para"},{"qrpc.payload","Payload","Payload"},{"qrpc.packet","Packet","Pacote"},{"qrpc.version","Version","Versão"},{"qrpc.hostToDevice","Host -> Device","Host -> Dispositivo"},{"qrpc.deviceToHost","Device -> Host","Dispositivo -> Host"},{"qrpc.frozen","Frozen packets: %zu   live buffer: %zu / 512","Pacotes congelados: %zu   buffer ao vivo: %zu / 512"},{"qrpc.buffered","Buffered packets: %zu / 512","Pacotes em buffer: %zu / 512"},{"qrpc.packetBytes","Packet bytes","Bytes do pacote"},{"qrpc.capture","%s %s   packet %u   %zu/%zu B captured","%s %s   pacote %u   %zu/%zu B capturados"},

            {"usb.description","USB connection, transport health and low-level transfer diagnostics live here.","Conexão USB, saúde do transporte e diagnósticos de baixo nível ficam aqui."},{"usb.connection","Connection","Conexão"},{"usb.connected","Connected","Conectado"},{"usb.disconnected","Disconnected","Desconectado"},{"usb.connect","Connect","Conectar"},{"usb.disconnect","Disconnect","Desconectar"},{"usb.autoReconnect","Auto reconnect","Reconectar automaticamente"},{"usb.deviceFirmware","Device %04X:%04X | firmware %s","Dispositivo %04X:%04X | firmware %s"},{"usb.frames","Frames sent %llu   dropped/busy %llu","Frames enviados %llu   perdidos/ocupados %llu"}
        });

        Language CurrentLanguage = Language::English;
        std::filesystem::path languagePath() { return settingsPath().parent_path() / "ui.language.ini"; }
    }

    Language language() noexcept { return CurrentLanguage; }

    const char* languageName(const Language value) noexcept
    {
        switch (value) { case Language::English:return "English"; case Language::PortugueseBrazil:return "Português (Brasil)"; case Language::Count:break; } return "English";
    }

    const char* tr(const std::string_view key) noexcept
    {
        for (const auto& entry:Catalog) { if (entry.Key!=key) continue; return CurrentLanguage==Language::PortugueseBrazil?entry.Portuguese:entry.English; } thread_local std::string fallback; fallback.assign(key); return fallback.c_str();
    }

    void setLanguage(const Language value) noexcept { CurrentLanguage=value>=Language::English&&value<Language::Count?value:Language::English; }

    void loadLanguagePreference() noexcept
    {
        try
        {
            std::ifstream file(languagePath()); if (file) { std::string line; while (std::getline(file,line)) { if (!line.starts_with("Language=")) continue; int value=0; if (parseNumber(std::string_view(line).substr(9),value)) setLanguage(static_cast<Language>(value)); return; } }
            if (const char* locale=std::getenv("LC_ALL");locale&&std::string_view(locale).starts_with("pt")) CurrentLanguage=Language::PortugueseBrazil; else if (const char* locale=std::getenv("LANG");locale&&std::string_view(locale).starts_with("pt")) CurrentLanguage=Language::PortugueseBrazil;
        }
        catch (...) {}
    }

    void saveLanguagePreference() noexcept
    {
        try { std::error_code ec; std::filesystem::create_directories(languagePath().parent_path(),ec); std::ofstream file(languagePath(),std::ios::trunc); if (file) file << "Language=" << static_cast<int>(CurrentLanguage) << '\n'; } catch (...) {}
    }

    bool drawLanguageSelector()
    {
        bool changed=false; ImGui::SetNextItemWidth(190.0f); if (ImGui::BeginCombo(tr("appearance.language"),languageName(CurrentLanguage))) { for (int i=0;i<static_cast<int>(Language::Count);++i) { const Language candidate=static_cast<Language>(i); const bool selected=candidate==CurrentLanguage; if (ImGui::Selectable(languageName(candidate),selected)) { CurrentLanguage=candidate; saveLanguagePreference(); changed=true; } if (selected) ImGui::SetItemDefaultFocus(); } ImGui::EndCombo(); } return changed;
    }
}
