#include "quartz/client/ui/I18n.hpp"
#include <array>

namespace quartz::client::ui::i18n
{
    namespace
    {
        struct Entry { std::string_view Key; const char* English; const char* Portuguese; };
        constexpr auto ReverseEngineeringCatalog=std::to_array<Entry>({
            {"re.instruction","Instruction","Instrução"},{"re.bytes","Bytes","Bytes"},{"re.ascii","ASCII","ASCII"},
            {"re.farFlow","Far control flow","Fluxo de controle distante"},{"re.farFlowCount","%zu cross-boundary routes","%zu rotas cruzando a janela"},{"re.farFlowTooltip","%zu far routes merged here. Click to inspect.","%zu rotas distantes mescladas aqui. Clique para inspecionar."},{"re.source","Source","Origem"},{"re.destination","Destination","Destino"},{"re.goSource","Go to source","Ir para origem"},{"re.goDestination","Go to destination","Ir para destino"},{"re.sourceInstruction","Source instruction","Instrução de origem"},{"re.destinationInstruction","Destination instruction","Instrução de destino"},
            {"re.functionPrologue","PROLOGUE","PRÓLOGO"},{"re.functionStart","FUNCTION START","INÍCIO DA FUNÇÃO"},{"re.functionEnd","END","FIM"},
            {"re.invalidAddress","Invalid address","Endereço inválido"},{"re.invalidMemoryAddress","Invalid memory address","Endereço de memória inválido"},{"re.selectAddressStatus","Select an address","Selecione um endereço"},
            {"re.executionProbeCancelled","Execution probe cancelled","Sonda de execução cancelada"},{"re.armedForNextExecution","Armed for next execution","Armado para a próxima execução"},{"re.armedFormat","ARMED %s - %s","ARMADO %s - %s"},{"re.armedProbeAt","Armed one-shot execution probe at %s","Sonda de execução de disparo único armada em %s"},
            {"re.registerValueTooltip","%s = %s\nunsigned: %llu\nsigned: %lld","%s = %s\nsem sinal: %llu\ncom sinal: %lld"},{"re.watchAddressFromRegister","Watch address field <- %s","Campo de endereço do monitor <- %s"},
            {"re.invalidValueTarget","Invalid value target","Alvo de valor inválido"},{"re.valueOutsideTypeRange","Value is outside the selected type range","O valor está fora do intervalo do tipo selecionado"},{"re.invalidPointerValue","Invalid pointer value","Valor de ponteiro inválido"},{"re.boolValueHint","Bool must be true/false, 1/0 or 0x1/0x0","Bool deve ser true/false, 1/0 ou 0x1/0x0"},
            {"re.invalidNumericValue","Invalid numeric value","Valor numérico inválido"},{"re.stringTooWide","String is wider than the watched value","A string é maior que o valor monitorado"},{"re.byteArrayWidthMismatch","Byte-array write must keep the watched width","A escrita do array de bytes deve manter a largura monitorada"},
            {"re.watchWidthUnknown","Cannot determine watched value width","Não foi possível determinar a largura do valor monitorado"},{"re.watchAlreadyExists","Value is already in the watch list","O valor já está na lista de monitoramento"},{"re.unreadable","<unreadable>","<ilegível>"},{"re.invalidWatchAddress","Invalid watch address","Endereço de monitoramento inválido"},{"re.invalidRange","Invalid range","Intervalo inválido"},
            {"re.regOriginalSyscall","Original syscall-number register saved by Linux ptrace state. Useful around syscall entry/exit; it is not a second accumulator value.","Registrador do número original da syscall salvo pelo estado do ptrace no Linux. Útil na entrada/saída de syscalls; não é um segundo valor do acumulador."},
            {"re.regVector","SIMD/vector register (XMM/YMM/ZMM family). Used for floating-point, packed integer and vector operations; wider names expose wider portions of the same architectural register.","Registrador SIMD/vetorial (família XMM/YMM/ZMM). Usado para ponto flutuante, inteiros empacotados e operações vetoriais; nomes mais largos expõem porções mais largas do mesmo registrador arquitetural."},
            {"re.regMmx","Legacy 64-bit MMX register. It aliases the x87 register storage and is uncommon in modern code.","Registrador MMX legado de 64 bits. Compartilha o armazenamento dos registradores x87 e é pouco comum em código moderno."},
            {"re.regX87","x87 floating-point stack register. ST(0) is the current top of the x87 register stack.","Registrador da pilha de ponto flutuante x87. ST(0) é o topo atual da pilha de registradores x87."},
            {"re.regControl","CPU control register. CR0/CR2/CR3/CR4 and related registers control processor modes, paging and fault state and are privileged.","Registrador de controle da CPU. CR0/CR2/CR3/CR4 e relacionados controlam modos do processador, paginação e estado de falhas e são privilegiados."},
            {"re.regDebug","Hardware debug register. DR0-DR3 hold breakpoint addresses and DR6/DR7 carry debug status/control.","Registrador de depuração de hardware. DR0-DR3 guardam endereços de breakpoint e DR6/DR7 mantêm estado/controle de depuração."},
            {"re.regMxcsr","SSE/AVX floating-point control and status register, including exception masks and rounding mode.","Registrador de controle e estado de ponto flutuante SSE/AVX, incluindo máscaras de exceção e modo de arredondamento."},
            {"re.asmNameMov","Move","Mover"},{"re.asmNameMovzx","Move Zero Extend","Mover com extensão por zero"},{"re.asmNameMovsx","Move Sign Extend","Mover com extensão de sinal"},{"re.asmNameLea","Load Effective Address","Carregar endereço efetivo"},{"re.asmNameXchg","Exchange","Trocar"},{"re.asmNameCmp","Compare","Comparar"},{"re.asmNameTest","Logical Compare","Comparação lógica"},{"re.asmNameAdd","Add","Somar"},{"re.asmNameSub","Subtract","Subtrair"},{"re.asmNameInc","Increment","Incrementar"},{"re.asmNameDec","Decrement","Decrementar"},{"re.asmNameAnd","Bitwise AND","AND bit a bit"},{"re.asmNameOr","Bitwise OR","OR bit a bit"},{"re.asmNameXor","Bitwise XOR","XOR bit a bit"},{"re.asmNameNot","Bitwise NOT","NOT bit a bit"},{"re.asmNameNeg","Negate","Negar"},{"re.asmNameMul","Unsigned Multiply","Multiplicação sem sinal"},{"re.asmNameImul","Signed Multiply","Multiplicação com sinal"},{"re.asmNameDiv","Unsigned Divide","Divisão sem sinal"},{"re.asmNameIdiv","Signed Divide","Divisão com sinal"},{"re.asmNameShl","Shift Left","Deslocar à esquerda"},{"re.asmNameShr","Logical Shift Right","Deslocamento lógico à direita"},{"re.asmNameSar","Arithmetic Shift Right","Deslocamento aritmético à direita"},{"re.asmNameCall","Call Procedure","Chamar procedimento"},{"re.asmNameRet","Return","Retornar"},{"re.asmNameJmp","Jump","Saltar"},{"re.asmNameJcc","Conditional Jump","Salto condicional"},{"re.asmNameCmov","Conditional Move","Movimento condicional"},{"re.asmNameSetcc","Set Byte on Condition","Definir byte por condição"},{"re.asmNamePush","Push to Stack","Empilhar"},{"re.asmNamePop","Pop from Stack","Desempilhar"},{"re.asmNameLeave","Leave Stack Frame","Sair do frame de pilha"},{"re.asmNameEnter","Enter Stack Frame","Entrar no frame de pilha"},{"re.asmNameInt","Software Interrupt","Interrupção por software"},{"re.asmNameSyscall","System Call","Chamada de sistema"},{"re.asmNameLoop","Loop","Laço"},{"re.asmNameBitTest","Bit Test","Teste de bit"},{"re.asmNameBswap","Byte Swap","Trocar ordem dos bytes"},{"re.asmNameNop","No Operation","Sem operação"},
            {"re.asmMovzx","Move a smaller source into a larger destination and zero-extend the high bits.","Move uma origem menor para um destino maior e estende os bits altos com zeros."},{"re.asmMovsx","Move a smaller source into a larger destination and sign-extend it.","Move uma origem menor para um destino maior e faz extensão de sinal."},{"re.asmXchg","Exchange the values of the two operands.","Troca os valores dos dois operandos."},
            {"re.asmAdd","Add the source to the destination and update arithmetic flags.","Soma a origem ao destino e atualiza as flags aritméticas."},{"re.asmSub","Subtract the source from the destination and update arithmetic flags.","Subtrai a origem do destino e atualiza as flags aritméticas."},{"re.asmInc","Increment the operand by one.","Incrementa o operando em um."},{"re.asmDec","Decrement the operand by one.","Decrementa o operando em um."},
            {"re.asmAnd","Bitwise AND. Commonly used for masks and flag-setting.","AND bit a bit. Comumente usado para máscaras e atualização de flags."},{"re.asmOr","Bitwise OR between the operands.","OR bit a bit entre os operandos."},{"re.asmXor","Bitwise XOR. XORing a register with itself is a common zeroing idiom.","XOR bit a bit. Fazer XOR de um registrador com ele mesmo é uma forma comum de zerá-lo."},{"re.asmNot","Invert every bit in the operand.","Inverte todos os bits do operando."},{"re.asmNeg","Two's-complement negate the operand.","Nega o operando em complemento de dois."},
            {"re.asmMul","Unsigned multiply using architecture-defined implicit accumulator operands/results.","Multiplicação sem sinal usando operandos/resultados implícitos definidos pela arquitetura."},{"re.asmImul","Signed integer multiply; forms vary between one, two and three operands.","Multiplicação inteira com sinal; possui formas de um, dois e três operandos."},{"re.asmDiv","Unsigned divide using implicit accumulator/data registers for dividend and remainder.","Divisão sem sinal usando registradores acumulador/dados implícitos para dividendo e resto."},{"re.asmIdiv","Signed integer divide using implicit accumulator/data registers.","Divisão inteira com sinal usando registradores acumulador/dados implícitos."},
            {"re.asmShl","Shift bits left; SAL is the arithmetic alias of SHL on x86.","Desloca bits para a esquerda; SAL é o alias aritmético de SHL no x86."},{"re.asmShr","Logical right shift; high bits are filled with zero.","Shift lógico para a direita; os bits altos são preenchidos com zero."},{"re.asmSar","Arithmetic right shift; preserves the sign bit.","Shift aritmético para a direita; preserva o bit de sinal."},
            {"re.asmCmov","Conditional move: copy the source only when the encoded flag condition is true.","Movimento condicional: copia a origem somente quando a condição de flags codificada é verdadeira."},{"re.asmSetcc","Write 0 or 1 to the destination according to a CPU-flag condition.","Escreve 0 ou 1 no destino de acordo com uma condição das flags da CPU."},
            {"re.asmLeave","Function-epilogue helper equivalent to restoring the stack pointer from the frame pointer and popping the old frame pointer.","Auxiliar de epílogo de função equivalente a restaurar o ponteiro da pilha a partir do frame pointer e desempilhar o frame pointer anterior."},{"re.asmEnter","Build a stack frame according to the encoded frame size/nesting level; uncommon in modern compiler output.","Cria um frame de pilha de acordo com tamanho/nível de aninhamento codificados; pouco comum em código de compiladores modernos."},
            {"re.asmInt","Software interrupt/trap instruction. INT3 is the one-byte breakpoint trap used by debuggers.","Instrução de interrupção/trap por software. INT3 é o trap de breakpoint de um byte usado por depuradores."},{"re.asmSyscall","Enter or leave an operating-system syscall path using the architecture-specific fast syscall mechanism.","Entra ou sai do caminho de syscall do sistema operacional usando o mecanismo rápido específico da arquitetura."},{"re.asmLoop","Decrement the loop counter register and branch according to the LOOP-family condition.","Decrementa o registrador contador de loop e desvia de acordo com a condição da família LOOP."},
            {"re.asmBitTest","Test, set, reset or complement a selected bit. The tested bit is reported through CF.","Testa, define, limpa ou complementa um bit selecionado. O bit testado é reportado pela CF."},{"re.asmBswap","Reverse the byte order of a register; commonly used for endian conversion.","Inverte a ordem dos bytes de um registrador; comumente usado para conversão de endianness."}
        });
    }

    const char* trExtension(const std::string_view key) noexcept
    {
        for (const auto& entry:ReverseEngineeringCatalog) if (entry.Key==key) return language()==Language::PortugueseBrazil?entry.Portuguese:entry.English; return nullptr;
    }
}
