#include "quartz/client/ui/pages/DevicePage.hpp"
#include "quartz/client/ui/PageContext.hpp"
#include "quartz/client/ui/PageManager.hpp"
#include "quartz/client/ui/I18n.hpp"

namespace quartz::client::ui
{
    void DevicePage::render(PageContext& context, PageManager& manager)
    {
        auto& usb=context.usb; const auto& keyboardInput=context.keyboardInput; auto& shaderFramebuffer=context.shaderFramebuffer; auto& settings=context.settings; auto& runtimeBindings=context.runtimeBindings; const auto sentFrames=context.sentFrames,droppedFrames=context.droppedFrames; const auto appCpuUsage=context.appCpuUsage; const auto scrollLockActive=context.scrollLockActive,capsLockActive=context.capsLockActive; const bool connected=usb.isConnected(); auto& deviceState=context.deviceState; PerformanceSnapshot performance{}; MatrixTimingProbeResult<ActiveProbeRows> timingProbe{}; bool hasPerformance=false,hasTimingProbe=false; std::uint64_t receivedPackets=0;
        { std::lock_guard lock(deviceState.Mutex); performance=deviceState.Performance; timingProbe=deviceState.TimingProbe; hasPerformance=deviceState.HasPerformance; hasTimingProbe=deviceState.HasTimingProbe; receivedPackets=deviceState.ReceivedPackets; }
        (void)manager; (void)performance; (void)timingProbe; (void)hasPerformance; (void)hasTimingProbe; const std::size_t framebufferPayloadBytes=sizeof(FramebufferSetPayload<MatrixSize>),framebufferPacketBytes=sizeof(PacketHeader)+framebufferPayloadBytes; const double configuredTxKiB=settings.Enabled&&settings.SendFramebuffer?framebufferPacketBytes*static_cast<double>(settings.FrameRate)/1024.0:0.0; const char* outputMode=settings.BaseColorMode==0?i18n::tr("visualizer.rgbWave"):settings.BaseColorMode==1?i18n::tr("visualizer.solid"):i18n::tr("visualizer.shader"); const char* shaderName=settings.ShaderPresetIndex==0?i18n::tr("shaders.customExternal"):ShaderPresets[static_cast<std::size_t>(settings.ShaderPresetIndex-1)].Name.c_str(); const bool pt=i18n::language()==i18n::Language::PortugueseBrazil;
        ImGui::SeparatorText(i18n::tr("device.identity")); ImGui::Text(i18n::tr("device.product"),connected?(usb.deviceName().empty()?"Quartz K552X":usb.deviceName().c_str()):i18n::tr("usb.disconnected")); ImGui::Text(i18n::tr("device.firmware"),FirmwareVersion); ImGui::Text("VID:PID: %04X:%04X",VendorId,ProductId); ImGui::Text(pt?"Protocolo QRPC: v%u   interface %d   OUT 0x%02X   IN 0x%02X":"QRPC protocol: v%u   interface %d   OUT 0x%02X   IN 0x%02X",static_cast<unsigned>(ProtocolVersion),RPCInterfaceNumber,static_cast<unsigned>(RPCOutEndpoint),static_cast<unsigned>(RPCInEndpoint)); ImGui::Text(i18n::tr("device.packetHeader"),sizeof(PacketHeader),framebufferPayloadBytes,framebufferPacketBytes); ImGui::Text(i18n::tr("device.logicalFramebuffer"),Columns,Rows,MatrixSize,Columns,ActiveProbeRows);
        ImGui::SeparatorText(i18n::tr("device.sessionOutput")); ImGui::Text(i18n::tr("device.uptimeCpu"),ImGui::GetTime(),appCpuUsage); ImGui::Text(i18n::tr("device.txStats"),static_cast<unsigned long long>(sentFrames),static_cast<unsigned long long>(droppedFrames),static_cast<unsigned long long>(receivedPackets)); ImGui::Text(i18n::tr("device.outputMode"),outputMode,settings.FrameRate,configuredTxKiB); if (settings.BaseColorMode==2) ImGui::Text(pt?"Sombreador: %s   alvo de renderização: %dx%d   modo de downsample: %d   parâmetros de material: %zu":"Shader: %s   render target: %dx%d   downsample mode: %d   material params: %zu",shaderName,settings.ShaderFramebufferWidth,settings.ShaderFramebufferHeight,settings.ShaderDownsampleMode,shaderFramebuffer.materialParameters().size()); ImGui::Text(i18n::tr("device.brightness"),settings.GlobalBrightness*100.0f,settings.LiveOutputInterpolation*100.0f);
        ImGui::SeparatorText(i18n::tr("device.hostInput")); ImGui::Text("evdev: %s",keyboardInput.connected()?i18n::tr("common.connected"):i18n::tr("common.disconnected")); if (!keyboardInput.deviceName().empty()) ImGui::Text(i18n::tr("device.inputDevice"),keyboardInput.deviceName().c_str()); ImGui::TextWrapped("%s",keyboardInput.status().c_str()); ImGui::Text(i18n::tr("device.locks"),capsLockActive?i18n::tr("common.on"):i18n::tr("common.off"),scrollLockActive?i18n::tr("common.on"):i18n::tr("common.off")); ImGui::TextDisabled("%s",i18n::tr("device.closeHint"));
        ImGui::SeparatorText(i18n::tr("device.runtimeFiles")); const std::string configFile=settingsPath().string(),vertexFile=vertexShaderPath().string(),fragmentFile=fragmentShaderPath().string(),materialFile=shaderMaterialPath().string(),bindingsFile=runtimeBindings.path().string(); ImGui::TextWrapped(i18n::tr("device.settingsFile"),configFile.c_str()); ImGui::TextWrapped(i18n::tr("device.vertexFile"),vertexFile.c_str()); ImGui::TextWrapped(i18n::tr("device.fragmentFile"),fragmentFile.c_str()); ImGui::TextWrapped(i18n::tr("device.materialFile"),materialFile.c_str()); ImGui::TextWrapped(i18n::tr("device.bindingsFile"),bindingsFile.c_str());
    }
}
