#include "quartz/client/ui/pages/JavaScriptPage.hpp"
#include "quartz/client/ui/PageContext.hpp"
#include "quartz/client/ui/PageManager.hpp"
#include "quartz/client/runtime/QuickJS.hpp"
#include <TextEditor.h>
#include <memory>
#include <unordered_map>

namespace quartz::client::ui
{
    namespace
    {
        const TextEditor::Language* javascriptLanguage()
        {
            static const TextEditor::Language language=[] { TextEditor::Language v;v.name="JavaScript";v.singleLineComment="//";v.commentStart="/*";v.commentEnd="*/";v.hasSingleQuotedStrings=true;v.hasDoubleQuotedStrings=true;v.otherStringStart="`";v.otherStringEnd="`";v.stringEscape='\\';v.keywords={"async","await","break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","from","function","get","if","import","in","instanceof","let","new","of","return","set","static","super","switch","this","throw","try","typeof","var","void","while","with","yield"};v.declarations={"true","false","null","undefined"};v.identifiers={"q","Math","JSON","BigInt","Number","String","Boolean","Array","Object","Map","Set","Date","RegExp","NaN","Infinity"};v.isPunctuation=[](const ImWchar c){return std::string_view("[]{}().,;:+-*/%<>=!&|^~?").find(static_cast<char>(c))!=std::string_view::npos;};return v;}();return &language;
        }
        struct EditorState{TextEditor Editor;std::string Synced;bool Init=false;};
        EditorState& editor(RuntimeScript& script){static std::unordered_map<std::uint64_t,std::unique_ptr<EditorState>> editors;auto[it,inserted]=editors.try_emplace(script.Id);if(inserted)it->second=std::make_unique<EditorState>();auto&s=*it->second;if(!s.Init){s.Editor.SetLanguage(javascriptLanguage());s.Editor.SetPalette(shaderEditorPalette());s.Editor.SetTabSize(4);s.Editor.SetInsertSpacesOnTabs(true);s.Editor.SetAutoIndentEnabled(true);s.Editor.SetShowLineNumbersEnabled(true);s.Editor.SetShowMatchingBrackets(true);s.Editor.SetText(script.Source);s.Synced=script.Source;s.Init=true;}else if(s.Synced!=script.Source){s.Editor.SetText(script.Source);s.Synced=script.Source;}return s;}
        struct KeyOption{const char*Name;int Key;};
        static constexpr KeyOption Keys[]={{"None",0},{"F1",GLFW_KEY_F1},{"F2",GLFW_KEY_F2},{"F3",GLFW_KEY_F3},{"F4",GLFW_KEY_F4},{"F5",GLFW_KEY_F5},{"F6",GLFW_KEY_F6},{"F7",GLFW_KEY_F7},{"F8",GLFW_KEY_F8},{"F9",GLFW_KEY_F9},{"F10",GLFW_KEY_F10},{"F11",GLFW_KEY_F11},{"F12",GLFW_KEY_F12},{"A",GLFW_KEY_A},{"B",GLFW_KEY_B},{"C",GLFW_KEY_C},{"D",GLFW_KEY_D},{"E",GLFW_KEY_E},{"F",GLFW_KEY_F},{"G",GLFW_KEY_G},{"H",GLFW_KEY_H},{"I",GLFW_KEY_I},{"J",GLFW_KEY_J},{"K",GLFW_KEY_K},{"L",GLFW_KEY_L},{"M",GLFW_KEY_M},{"N",GLFW_KEY_N},{"O",GLFW_KEY_O},{"P",GLFW_KEY_P},{"Q",GLFW_KEY_Q},{"R",GLFW_KEY_R},{"S",GLFW_KEY_S},{"T",GLFW_KEY_T},{"U",GLFW_KEY_U},{"V",GLFW_KEY_V},{"W",GLFW_KEY_W},{"X",GLFW_KEY_X},{"Y",GLFW_KEY_Y},{"Z",GLFW_KEY_Z},{"0",GLFW_KEY_0},{"1",GLFW_KEY_1},{"2",GLFW_KEY_2},{"3",GLFW_KEY_3},{"4",GLFW_KEY_4},{"5",GLFW_KEY_5},{"6",GLFW_KEY_6},{"7",GLFW_KEY_7},{"8",GLFW_KEY_8},{"9",GLFW_KEY_9}};
    }

    void JavaScriptPage::render(PageContext& context,PageManager& manager)
    {
        auto& engine=context.runtimeBindings;auto& settings=engine.scriptSettings();static std::string status;
        ImGui::TextWrapped("First-class QuickJS runtime automation. Workspace scripts run outside binding evaluation, so they can safely create/configure bindings, controls, banks, profiles, object models and pointers, then drive shader/runtime outputs.");
        if(ImGui::Button("+ Inline script")){auto&s=engine.addScript();s.Source="// q.graph.*, q.runtime.*, q.re.* and q.import() are available here.\n";}ImGui::SameLine();if(ImGui::Button("+ External script")){auto&s=engine.addScript();s.External=true;s.Path=(runtimeQuickJSScriptDirectory()/"script.js").string();}ImGui::SameLine();if(ImGui::Button("Reload all")){runtimeReloadAllWorkspaceScripts();status="all script contexts reloaded";}ImGui::SameLine();if(ImGui::Button("Save .d.ts")){std::string error;status=runtimeSaveQuickJSTypeDeclarations(error)?"saved "+runtimeQuickJSTypeDeclarationsPath().string():error;}
        if(!status.empty())ImGui::TextDisabled("%s",status.c_str());
        bool changed=false;changed|=ImGui::Checkbox("External script hot reload",&settings.ExternalHotReload);ImGui::SameLine();ImGui::TextDisabled("polls main scripts + q.import() dependencies and rebuilds the context on change");
        ImGui::SeparatorText("Global reload hotkey");changed|=ImGui::Checkbox("Ctrl##jsReload",&settings.ReloadHotkeyCtrl);ImGui::SameLine();changed|=ImGui::Checkbox("Alt##jsReload",&settings.ReloadHotkeyAlt);ImGui::SameLine();changed|=ImGui::Checkbox("Shift##jsReload",&settings.ReloadHotkeyShift);ImGui::SameLine();const char*preview="None";for(const auto&k:Keys)if(k.Key==settings.ReloadHotkeyKey){preview=k.Name;break;}ImGui::SetNextItemWidth(100);if(ImGui::BeginCombo("Key##jsReload",preview)){for(const auto&k:Keys){const bool selected=k.Key==settings.ReloadHotkeyKey;if(ImGui::Selectable(k.Name,selected)){settings.ReloadHotkeyKey=k.Key;changed=true;}if(selected)ImGui::SetItemDefaultFocus();}ImGui::EndCombo();}ImGui::SameLine();ImGui::TextDisabled("uses evdev globally; GLFW fallback");if(changed)engine.markChanged();
        ImGui::SeparatorText("Workspace scripts");std::optional<std::size_t> erase;
        for(std::size_t i=0;i<engine.scripts().size();++i){auto&script=engine.scripts()[i];ImGui::PushID(static_cast<int>(script.Id&0x7fffffffULL));const std::string header=std::string(script.Name)+(script.Enabled?"":"  DISABLED")+"###RuntimeScript"+std::to_string(script.Id);if(ImGui::CollapsingHeader(header.c_str(),ImGuiTreeNodeFlags_DefaultOpen)){bool local=false;local|=ImGui::Checkbox("Enabled",&script.Enabled);ImGui::SameLine();ImGui::SetNextItemWidth(240);local|=ImGui::InputText("Name",script.Name,sizeof(script.Name));ImGui::SameLine();local|=ImGui::Checkbox("External",&script.External);ImGui::SameLine();if(ImGui::SmallButton("Reload")){runtimeResetWorkspaceScript(script.Id);++script.ReloadCount;}ImGui::SameLine();if(ImGui::SmallButton("Remove"))erase=i;
            ImGui::SetNextItemWidth(160);local|=ImGui::DragFloat("Update Hz",&script.UpdateHz,0.5f,0.5f,500.0f,"%.1f");ImGui::SameLine();ImGui::SetNextItemWidth(150);local|=ImGui::DragFloat("Timeout",&script.TimeoutMs,0.1f,0.1f,100.0f,"%.1f ms");ImGui::SameLine();local|=ImGui::Checkbox("Hot reload##script",&script.HotReload);ImGui::SetNextItemWidth(180);local|=ImGui::InputText("Group",script.Group,sizeof(script.Group));ImGui::SameLine();ImGui::SetNextItemWidth(80);local|=ImGui::InputInt("Order",&script.Order);
            if(script.External){char path[1024]{};std::snprintf(path,sizeof(path),"%s",script.Path.c_str());ImGui::SetNextItemWidth(-1);if(ImGui::InputText("Path",path,sizeof(path))){script.Path=path;local=true;}ImGui::TextDisabled("Relative paths resolve under %s",runtimeQuickJSScriptDirectory().string().c_str());}
            else{auto&e=editor(script);e.Editor.Render("##WorkspaceScriptEditor",ImVec2(-1,300));const std::string edited=e.Editor.GetText();if(edited!=e.Synced){script.Source=edited;e.Synced=script.Source;runtimeResetWorkspaceScript(script.Id);local=true;}}
            ImGui::Text("Runs %llu  compiles %llu  reloads %llu  timeouts %llu  last %.3f ms",static_cast<unsigned long long>(script.RunCount),static_cast<unsigned long long>(script.CompileCount),static_cast<unsigned long long>(script.ReloadCount),static_cast<unsigned long long>(script.TimeoutCount),script.LastMilliseconds);if(!script.Status.empty())ImGui::TextWrapped("Status: %s",script.Status.c_str());if(!script.LastLog.empty())ImGui::TextWrapped("Log: %s",script.LastLog.c_str());if(!script.Dependencies.empty()&&ImGui::TreeNode("Imported dependencies")){for(const auto&dep:script.Dependencies)ImGui::BulletText("%s",dep.c_str());ImGui::TreePop();}if(local)engine.markChanged();}
            ImGui::Separator();ImGui::PopID();}
        if(erase)engine.eraseScript(*erase);
        ImGui::SeparatorText("Graph access");ImGui::TextWrapped("Scripts can configure the same graph exposed by the tabs: q.graph.ensureBinding/ensureControl/ensureBank/ensureObject/ensurePointer/ensureProfile, binding operations, enable/disable/remove nodes and profile activation. q.runtime drives shaders/materials/brightness/framebuffer state immediately. q.re exposes process memory/signatures/disassembly.");if(ImGui::Button("Open Bindings"))manager.open("bindings");ImGui::SameLine();if(ImGui::Button("Open Controls"))manager.open("controls");ImGui::SameLine();if(ImGui::Button("Open Profiles"))manager.open("profiles");
    }
}
